##version: 1.0.0
CREATE TABLE info (DB_SCHEMA_VERSION VARCHAR(8));
INSERT INTO info VALUES ("1.0.0");

##version: 1.1.0
CREATE TABLE sample_list LIKE patient_list;
INSERT sample_list SELECT * FROM patient_list;
CREATE TABLE sample_list_list LIKE patient_list_list;
INSERT sample_list_list SELECT * FROM patient_list_list;
ALTER TABLE sample_list_list CHANGE PATIENT_ID SAMPLE_ID INT(11);
UPDATE info SET DB_SCHEMA_VERSION="1.1.0";

##version: 1.2.0
ALTER TABLE cna_event AUTO_INCREMENT=1;
ALTER TABLE mutation add UNIQUE KEY `UQ_MUTATION_EVENT_ID_GENETIC_PROFILE_ID_SAMPLE_ID` (`MUTATION_EVENT_ID`,`GENETIC_PROFILE_ID`,`SAMPLE_ID`);
ALTER TABLE sample_profile add UNIQUE KEY `UQ_SAMPLE_ID_GENETIC_PROFILE_ID` (`SAMPLE_ID`,`GENETIC_PROFILE_ID`);
UPDATE info SET DB_SCHEMA_VERSION="1.2.0";

##version: 1.2.1
SET @s = (SELECT IF(    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'cancer_study' AND table_schema = DATABASE() AND column_name = 'STATUS') > 0,  "SELECT 1", " ALTER TABLE cancer_study ADD STATUS int(1) DEFAULT NULL"));
PREPARE stmt FROM @s;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
UPDATE info SET DB_SCHEMA_VERSION="1.2.1";

##version: 1.2.2
CREATE TABLE gene_panel (
	INTERNAL_ID int(11) NOT NULL auto_increment,
	STABLE_ID varchar(255) NOT NULL,
	DESCRIPTION mediumtext,
	PRIMARY KEY (INTERNAL_ID),
	UNIQUE (STABLE_ID)
);

CREATE TABLE gene_panel_list (
	INTERNAL_ID int(11) NOT NULL,
	GENE_ID int(255) NOT NULL,
	PRIMARY KEY (INTERNAL_ID, GENE_ID),
	FOREIGN KEY (INTERNAL_ID) REFERENCES gene_panel (INTERNAL_ID) ON DELETE CASCADE,
	FOREIGN KEY (GENE_ID) REFERENCES gene (ENTREZ_GENE_ID) ON DELETE CASCADE
);

CREATE TABLE gene_panel_profile_map (
	SAMPLE_ID int(11) NOT NULL,
	PROFILE_ID int(11) NOT NULL,
	PANEL_ID int(11) NOT NULL,
	PRIMARY KEY (SAMPLE_ID, PROFILE_ID),
	FOREIGN KEY (SAMPLE_ID) REFERENCES sample (INTERNAL_ID) ON DELETE CASCADE,
	FOREIGN KEY (PROFILE_ID) REFERENCES genetic_profile (GENETIC_PROFILE_ID) ON DELETE CASCADE,
	FOREIGN KEY (PANEL_ID) REFERENCES gene_panel (INTERNAL_ID) ON DELETE CASCADE
);

UPDATE info SET DB_SCHEMA_VERSION="1.2.2";
