##version: 1.0.0
CREATE TABLE info (DB_SCHEMA_VERSION VARCHAR(8));
INSERT INTO info VALUES ("1.0.0");

##version: 1.1.0
CREATE TABLE sample_list LIKE patient_list;
INSERT sample_list SELECT * FROM patient_list;
CREATE TABLE sample_list_list LIKE patient_list_list;
INSERT sample_list_list SELECT * FROM patient_list_list;
ALTER TABLE sample_list_list CHANGE PATIENT_ID SAMPLE_ID INT(11);
UPDATE info SET DB_SCHEMA_VERSION="1.1.0";

##version: 1.2.0
CREATE TABLE gene_panel (
    INTERNAL_ID int(11) NOT NULL auto_increment,
    STABLE_ID varchar(255) NOT NULL,
    DESCRIPTION mediumtext,
    CANCER_STUDY_ID int(11) NOT NULL,
    PRIMARY KEY (INTERNAL_ID),
    FOREIGN KEY (CANCER_STUDY_ID) REFERENCES cancer_study (CANCER_STUDY_ID) ON DELETE CASCADE,
    UNIQUE (STABLE_ID)
);

CREATE TABLE gene_panel_list (
  INTERNAL_ID int(11) NOT NULL,
  GENE_ID int(255) NOT NULL,
  PRIMARY KEY  (INTERNAL_ID, GENE_ID),
  FOREIGN KEY (INTERNAL_ID) REFERENCES gene_panel (INTERNAL_ID) ON DELETE CASCADE,
  FOREIGN KEY (GENE_ID) REFERENCES gene (ENTREZ_GENE_ID) ON DELETE CASCADE
);
