package org.mskcc.cbio.importer.cvr.darwin.model;

public class ClinicalNote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CLINICAL_NOTES_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer CLNT_CLINICAL_NOTES_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer CLNT_PT_DEIDENTIFICATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer CLNT_DAYS_SINCE_MRN_CREATE_DTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer CLNT_YEARS_SINCE_BIRTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_DT_DAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_DT_WEEKDAY_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_MONTH_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Short CLNT_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CATEGORY
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_CATEGORY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOCTYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_DOCTYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_EMR_DESC
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_EMR_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOC_FORMAT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_DOC_FORMAT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DEID_MEDICAL_DOCUMENT_TXT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String CLNT_DEID_MEDICAL_DOCUMENT_TXT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CLINICAL_NOTES_ID
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_CLINICAL_NOTES_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getCLNT_CLINICAL_NOTES_ID() {
        return CLNT_CLINICAL_NOTES_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CLINICAL_NOTES_ID
     *
     * @param CLNT_CLINICAL_NOTES_ID the value for DVCBIO.CLINICAL_NOTE_V.CLNT_CLINICAL_NOTES_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_CLINICAL_NOTES_ID(Integer CLNT_CLINICAL_NOTES_ID) {
        this.CLNT_CLINICAL_NOTES_ID = CLNT_CLINICAL_NOTES_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_PT_DEIDENTIFICATION_ID
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getCLNT_PT_DEIDENTIFICATION_ID() {
        return CLNT_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_PT_DEIDENTIFICATION_ID
     *
     * @param CLNT_PT_DEIDENTIFICATION_ID the value for DVCBIO.CLINICAL_NOTE_V.CLNT_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_PT_DEIDENTIFICATION_ID(Integer CLNT_PT_DEIDENTIFICATION_ID) {
        this.CLNT_PT_DEIDENTIFICATION_ID = CLNT_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getCLNT_DAYS_SINCE_MRN_CREATE_DTE() {
        return CLNT_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @param CLNT_DAYS_SINCE_MRN_CREATE_DTE the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DAYS_SINCE_MRN_CREATE_DTE(Integer CLNT_DAYS_SINCE_MRN_CREATE_DTE) {
        this.CLNT_DAYS_SINCE_MRN_CREATE_DTE = CLNT_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEARS_SINCE_BIRTH
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getCLNT_YEARS_SINCE_BIRTH() {
        return CLNT_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEARS_SINCE_BIRTH
     *
     * @param CLNT_YEARS_SINCE_BIRTH the value for DVCBIO.CLINICAL_NOTE_V.CLNT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_YEARS_SINCE_BIRTH(Integer CLNT_YEARS_SINCE_BIRTH) {
        this.CLNT_YEARS_SINCE_BIRTH = CLNT_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_DAY_NAME
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_DT_DAY_NAME() {
        return CLNT_DT_DAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_DAY_NAME
     *
     * @param CLNT_DT_DAY_NAME the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DT_DAY_NAME(String CLNT_DT_DAY_NAME) {
        this.CLNT_DT_DAY_NAME = CLNT_DT_DAY_NAME == null ? null : CLNT_DT_DAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_WEEKDAY_FLAG
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_DT_WEEKDAY_FLAG() {
        return CLNT_DT_WEEKDAY_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DT_WEEKDAY_FLAG
     *
     * @param CLNT_DT_WEEKDAY_FLAG the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DT_WEEKDAY_FLAG(String CLNT_DT_WEEKDAY_FLAG) {
        this.CLNT_DT_WEEKDAY_FLAG = CLNT_DT_WEEKDAY_FLAG == null ? null : CLNT_DT_WEEKDAY_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_MONTH_NAME
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_MONTH_NAME() {
        return CLNT_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_MONTH_NAME
     *
     * @param CLNT_MONTH_NAME the value for DVCBIO.CLINICAL_NOTE_V.CLNT_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_MONTH_NAME(String CLNT_MONTH_NAME) {
        this.CLNT_MONTH_NAME = CLNT_MONTH_NAME == null ? null : CLNT_MONTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEAR
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Short getCLNT_YEAR() {
        return CLNT_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_YEAR
     *
     * @param CLNT_YEAR the value for DVCBIO.CLINICAL_NOTE_V.CLNT_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_YEAR(Short CLNT_YEAR) {
        this.CLNT_YEAR = CLNT_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CATEGORY
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_CATEGORY
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_CATEGORY() {
        return CLNT_CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_CATEGORY
     *
     * @param CLNT_CATEGORY the value for DVCBIO.CLINICAL_NOTE_V.CLNT_CATEGORY
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_CATEGORY(String CLNT_CATEGORY) {
        this.CLNT_CATEGORY = CLNT_CATEGORY == null ? null : CLNT_CATEGORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOCTYPE
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DOCTYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_DOCTYPE() {
        return CLNT_DOCTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOCTYPE
     *
     * @param CLNT_DOCTYPE the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DOCTYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DOCTYPE(String CLNT_DOCTYPE) {
        this.CLNT_DOCTYPE = CLNT_DOCTYPE == null ? null : CLNT_DOCTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_EMR_DESC
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_EMR_DESC
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_EMR_DESC() {
        return CLNT_EMR_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_EMR_DESC
     *
     * @param CLNT_EMR_DESC the value for DVCBIO.CLINICAL_NOTE_V.CLNT_EMR_DESC
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_EMR_DESC(String CLNT_EMR_DESC) {
        this.CLNT_EMR_DESC = CLNT_EMR_DESC == null ? null : CLNT_EMR_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOC_FORMAT
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DOC_FORMAT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_DOC_FORMAT() {
        return CLNT_DOC_FORMAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DOC_FORMAT
     *
     * @param CLNT_DOC_FORMAT the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DOC_FORMAT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DOC_FORMAT(String CLNT_DOC_FORMAT) {
        this.CLNT_DOC_FORMAT = CLNT_DOC_FORMAT == null ? null : CLNT_DOC_FORMAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DEID_MEDICAL_DOCUMENT_TXT
     *
     * @return the value of DVCBIO.CLINICAL_NOTE_V.CLNT_DEID_MEDICAL_DOCUMENT_TXT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getCLNT_DEID_MEDICAL_DOCUMENT_TXT() {
        return CLNT_DEID_MEDICAL_DOCUMENT_TXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.CLINICAL_NOTE_V.CLNT_DEID_MEDICAL_DOCUMENT_TXT
     *
     * @param CLNT_DEID_MEDICAL_DOCUMENT_TXT the value for DVCBIO.CLINICAL_NOTE_V.CLNT_DEID_MEDICAL_DOCUMENT_TXT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setCLNT_DEID_MEDICAL_DOCUMENT_TXT(String CLNT_DEID_MEDICAL_DOCUMENT_TXT) {
        this.CLNT_DEID_MEDICAL_DOCUMENT_TXT = CLNT_DEID_MEDICAL_DOCUMENT_TXT == null ? null : CLNT_DEID_MEDICAL_DOCUMENT_TXT.trim();
    }
}