package org.mskcc.cbio.importer.cvr.darwin.model;

public class SequenomResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer SEQ_PT_DEIDENTIFICATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_GENE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_GENE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_RESULT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_RESULT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_LOCUS
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_LOCUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_AMINO_ACID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_AMINO_ACID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_NUCLEOTIDE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_NUCLEOTIDE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DETAIL
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_DETAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_ABERRATION_TYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_ABERRATION_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer SEQ_DAYS_SINCE_MRN_CREATE_DTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Integer SEQ_YEARS_SINCE_BIRTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_DT_DAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_DT_WEEKDAY_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private String SEQ_MONTH_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    private Short SEQ_YEAR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_PT_DEIDENTIFICATION_ID
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getSEQ_PT_DEIDENTIFICATION_ID() {
        return SEQ_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_PT_DEIDENTIFICATION_ID
     *
     * @param SEQ_PT_DEIDENTIFICATION_ID the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_PT_DEIDENTIFICATION_ID(Integer SEQ_PT_DEIDENTIFICATION_ID) {
        this.SEQ_PT_DEIDENTIFICATION_ID = SEQ_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_GENE
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_GENE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_GENE() {
        return SEQ_GENE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_GENE
     *
     * @param SEQ_GENE the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_GENE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_GENE(String SEQ_GENE) {
        this.SEQ_GENE = SEQ_GENE == null ? null : SEQ_GENE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_RESULT
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_RESULT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_RESULT() {
        return SEQ_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_RESULT
     *
     * @param SEQ_RESULT the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_RESULT
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_RESULT(String SEQ_RESULT) {
        this.SEQ_RESULT = SEQ_RESULT == null ? null : SEQ_RESULT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_LOCUS
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_LOCUS
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_LOCUS() {
        return SEQ_LOCUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_LOCUS
     *
     * @param SEQ_LOCUS the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_LOCUS
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_LOCUS(String SEQ_LOCUS) {
        this.SEQ_LOCUS = SEQ_LOCUS == null ? null : SEQ_LOCUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_AMINO_ACID
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_AMINO_ACID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_AMINO_ACID() {
        return SEQ_AMINO_ACID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_AMINO_ACID
     *
     * @param SEQ_AMINO_ACID the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_AMINO_ACID
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_AMINO_ACID(String SEQ_AMINO_ACID) {
        this.SEQ_AMINO_ACID = SEQ_AMINO_ACID == null ? null : SEQ_AMINO_ACID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_NUCLEOTIDE
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_NUCLEOTIDE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_NUCLEOTIDE() {
        return SEQ_NUCLEOTIDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_NUCLEOTIDE
     *
     * @param SEQ_NUCLEOTIDE the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_NUCLEOTIDE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_NUCLEOTIDE(String SEQ_NUCLEOTIDE) {
        this.SEQ_NUCLEOTIDE = SEQ_NUCLEOTIDE == null ? null : SEQ_NUCLEOTIDE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DETAIL
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_DETAIL
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_DETAIL() {
        return SEQ_DETAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DETAIL
     *
     * @param SEQ_DETAIL the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_DETAIL
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_DETAIL(String SEQ_DETAIL) {
        this.SEQ_DETAIL = SEQ_DETAIL == null ? null : SEQ_DETAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_ABERRATION_TYPE
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_ABERRATION_TYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_ABERRATION_TYPE() {
        return SEQ_ABERRATION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_ABERRATION_TYPE
     *
     * @param SEQ_ABERRATION_TYPE the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_ABERRATION_TYPE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_ABERRATION_TYPE(String SEQ_ABERRATION_TYPE) {
        this.SEQ_ABERRATION_TYPE = SEQ_ABERRATION_TYPE == null ? null : SEQ_ABERRATION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getSEQ_DAYS_SINCE_MRN_CREATE_DTE() {
        return SEQ_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @param SEQ_DAYS_SINCE_MRN_CREATE_DTE the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_DAYS_SINCE_MRN_CREATE_DTE(Integer SEQ_DAYS_SINCE_MRN_CREATE_DTE) {
        this.SEQ_DAYS_SINCE_MRN_CREATE_DTE = SEQ_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEARS_SINCE_BIRTH
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Integer getSEQ_YEARS_SINCE_BIRTH() {
        return SEQ_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEARS_SINCE_BIRTH
     *
     * @param SEQ_YEARS_SINCE_BIRTH the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_YEARS_SINCE_BIRTH(Integer SEQ_YEARS_SINCE_BIRTH) {
        this.SEQ_YEARS_SINCE_BIRTH = SEQ_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_DAY_NAME
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_DT_DAY_NAME() {
        return SEQ_DT_DAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_DAY_NAME
     *
     * @param SEQ_DT_DAY_NAME the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_DAY_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_DT_DAY_NAME(String SEQ_DT_DAY_NAME) {
        this.SEQ_DT_DAY_NAME = SEQ_DT_DAY_NAME == null ? null : SEQ_DT_DAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_WEEKDAY_FLAG
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_DT_WEEKDAY_FLAG() {
        return SEQ_DT_WEEKDAY_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_WEEKDAY_FLAG
     *
     * @param SEQ_DT_WEEKDAY_FLAG the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_DT_WEEKDAY_FLAG(String SEQ_DT_WEEKDAY_FLAG) {
        this.SEQ_DT_WEEKDAY_FLAG = SEQ_DT_WEEKDAY_FLAG == null ? null : SEQ_DT_WEEKDAY_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_MONTH_NAME
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public String getSEQ_MONTH_NAME() {
        return SEQ_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_MONTH_NAME
     *
     * @param SEQ_MONTH_NAME the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_MONTH_NAME
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_MONTH_NAME(String SEQ_MONTH_NAME) {
        this.SEQ_MONTH_NAME = SEQ_MONTH_NAME == null ? null : SEQ_MONTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEAR
     *
     * @return the value of DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public Short getSEQ_YEAR() {
        return SEQ_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEAR
     *
     * @param SEQ_YEAR the value for DVCBIO.SEQUENOM_RESULTS_V.SEQ_YEAR
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    public void setSEQ_YEAR(Short SEQ_YEAR) {
        this.SEQ_YEAR = SEQ_YEAR;
    }
}