name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🧬 Features'
    labels:
      - 'feature'
      - 'cl-feature'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
      - 'cl-enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'cl-bug'
  - title: '🏎 Performance Tweaks'
    labels:
      - 'performance'
      - 'cl-performance'
  - title: '🎨 Style Tweaks'
    labels:
      - 'style tweak'
      - 'cl-style-tweak'
  - title: '⚙️ REST API Changes'
    labels:
      - 'api'
  - title: '⚙️ Changes to handle external APIs'
    labels:
      - 'external api'
      - 'cl-external-api'
  - title: '🗄 Database Migration'
    labels:
      - 'includes db changes'
      - 'migration'
      - 'cl-db-migration'
  - title: '⚠️ Deprecation'
    labels:
      - 'deprecation'
      - 'cl-deprecation'
  - title: '📘 Documentation'
    labels:
      - 'documentation'
      - 'cl-documentation'
  - title: '🧹 Cleanup & Refactoring 🔧'
    labels:
      - 'cleanup'
      - 'refactoring'
      - 'cl-refactoring'
  - title: '👷‍♀️ Testing, Configuration & Deployment'
    labels:
      - 'devops'
      - 'test'
      - 'cl-test'
      - 'cl-devops'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'cl-chore'
  - title: '📐 Prototype (Internal Use)'
    labels:
      - 'cl-prototype'
exclude-labels:
  - 'skip-changelog'
  - 'cl-skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
  
  ## 🕵️‍♀️ Full commit logs
  
  - Backend: https://github.com/cBioPortal/cbioportal/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
  - Frontend: https://github.com/cBioPortal/cbioportal-frontend/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
  
  ## 🏷Notes on versioning and release procedure
  https://docs.cbioportal.org/4.-development/release-procedure#a-note-on-versioning
