engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  csslint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.go"
   - "**.css"
   - "**.js"
   - "**.jsx"
   - "**.py"
exclude_paths:
- spec/**/*
- vendor/**/*
- "test/*"
