
package org.foundation;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CaseInfoService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://mskcc.foundationmedicine.com/Fmi.CaseInfoService/CaseInfoService.svc?wsdl")
public class CaseInfoService
    extends Service
{

    private final static URL CASEINFOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(CaseInfoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = CaseInfoService.class.getResource(".");
            url = new URL(baseUrl, "https://mskcc.foundationmedicine.com/Fmi.CaseInfoService/CaseInfoService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://mskcc.foundationmedicine.com/Fmi.CaseInfoService/CaseInfoService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CASEINFOSERVICE_WSDL_LOCATION = url;
    }

    public CaseInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaseInfoService() {
        super(CASEINFOSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "CaseInfoService"));
    }

    /**
     * 
     * @return
     *     returns ICaseInfoService
     */
    @WebEndpoint(name = "ICaseInfoService")
    public ICaseInfoService getICaseInfoService() {
        return super.getPort(new QName("http://tempuri.org/", "ICaseInfoService"), ICaseInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICaseInfoService
     */
    @WebEndpoint(name = "ICaseInfoService")
    public ICaseInfoService getICaseInfoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ICaseInfoService"), ICaseInfoService.class, features);
    }

}
