apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: cbioportal-jre
  name: cbioportal-jre
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cbioportal-jre
spec:
  replicas: 1
  selector:
    matchLabels:
        run: cbioportal-jre
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cbioportal-jre
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: CBIOPORTAL_DB_HOST
          value: "sm4sa6ozhn5ya6.cuooweljyhix.us-east-1.rds.amazonaws.com"
        - name: CBIOPORTAL_DB_CONNECTION_STRING
          value: "jdbc:mysql://sm4sa6ozhn5ya6.cuooweljyhix.us-east-1.rds.amazonaws.com:3306/"
        image: inodb/cbioportal-jre:v1.12.0-8-ga4d3e20e1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
        name: cbioportal-jre
        ports:
        - containerPort: 80
          name: http
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
