//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 10:50:18 AM EDT 
//


package org.mskcc.cbio.foundation.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.foundation.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClientCaseInfo_QNAME = new QName("", "ClientCaseInfo");
    private final static QName _VariantReportTypeRearrangementsRearrangement_QNAME = new QName("", "rearrangement");
    private final static QName _SampleTypeComment_QNAME = new QName("", "comment");
    private final static QName _CopyNumberAlterationsTypeCopyNumberAlteration_QNAME = new QName("", "copy-number-alteration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.foundation.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VariantReportType }
     * 
     */
    public VariantReportType createVariantReportType() {
        return new VariantReportType();
    }

    /**
     * Create an instance of {@link ClientCaseInfoType }
     * 
     */
    public ClientCaseInfoType createClientCaseInfoType() {
        return new ClientCaseInfoType();
    }

    /**
     * Create an instance of {@link CopyNumberAlterationsType }
     * 
     */
    public CopyNumberAlterationsType createCopyNumberAlterationsType() {
        return new CopyNumberAlterationsType();
    }

    /**
     * Create an instance of {@link CasesType }
     * 
     */
    public CasesType createCasesType() {
        return new CasesType();
    }

    /**
     * Create an instance of {@link CaseType }
     * 
     */
    public CaseType createCaseType() {
        return new CaseType();
    }

    /**
     * Create an instance of {@link RearrangementsType }
     * 
     */
    public RearrangementsType createRearrangementsType() {
        return new RearrangementsType();
    }

    /**
     * Create an instance of {@link SamplesType }
     * 
     */
    public SamplesType createSamplesType() {
        return new SamplesType();
    }

    /**
     * Create an instance of {@link MetricsType }
     * 
     */
    public MetricsType createMetricsType() {
        return new MetricsType();
    }

    /**
     * Create an instance of {@link QualityControlType }
     * 
     */
    public QualityControlType createQualityControlType() {
        return new QualityControlType();
    }

    /**
     * Create an instance of {@link ShortVariantsType }
     * 
     */
    public ShortVariantsType createShortVariantsType() {
        return new ShortVariantsType();
    }

    /**
     * Create an instance of {@link MetricType }
     * 
     */
    public MetricType createMetricType() {
        return new MetricType();
    }

    /**
     * Create an instance of {@link ShortVariantType }
     * 
     */
    public ShortVariantType createShortVariantType() {
        return new ShortVariantType();
    }

    /**
     * Create an instance of {@link RearrangementType }
     * 
     */
    public RearrangementType createRearrangementType() {
        return new RearrangementType();
    }

    /**
     * Create an instance of {@link SampleType }
     * 
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link CopyNumberAlterationType }
     * 
     */
    public CopyNumberAlterationType createCopyNumberAlterationType() {
        return new CopyNumberAlterationType();
    }

    /**
     * Create an instance of {@link VariantReportType.Rearrangements }
     * 
     */
    public VariantReportType.Rearrangements createVariantReportTypeRearrangements() {
        return new VariantReportType.Rearrangements();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientCaseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClientCaseInfo")
    public JAXBElement<ClientCaseInfoType> createClientCaseInfo(ClientCaseInfoType value) {
        return new JAXBElement<ClientCaseInfoType>(_ClientCaseInfo_QNAME, ClientCaseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RearrangementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rearrangement", scope = VariantReportType.Rearrangements.class)
    public JAXBElement<RearrangementType> createVariantReportTypeRearrangementsRearrangement(RearrangementType value) {
        return new JAXBElement<RearrangementType>(_VariantReportTypeRearrangementsRearrangement_QNAME, RearrangementType.class, VariantReportType.Rearrangements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment", scope = SampleType.class)
    public JAXBElement<String> createSampleTypeComment(String value) {
        return new JAXBElement<String>(_SampleTypeComment_QNAME, String.class, SampleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CopyNumberAlterationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "copy-number-alteration", scope = CopyNumberAlterationsType.class)
    public JAXBElement<CopyNumberAlterationType> createCopyNumberAlterationsTypeCopyNumberAlteration(CopyNumberAlterationType value) {
        return new JAXBElement<CopyNumberAlterationType>(_CopyNumberAlterationsTypeCopyNumberAlteration_QNAME, CopyNumberAlterationType.class, CopyNumberAlterationsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment", scope = RearrangementType.class)
    public JAXBElement<String> createRearrangementTypeComment(String value) {
        return new JAXBElement<String>(_SampleTypeComment_QNAME, String.class, RearrangementType.class, value);
    }

}
