//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 10:50:18 AM EDT 
//


package org.mskcc.cbio.foundation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for short-variantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="short-variantType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="cds-effect" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="depth" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="functional-effect" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gene" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="percent-reads" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protein-effect" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="strand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transcript" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "short-variantType", propOrder = {
    "value"
})
public class ShortVariantType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "cds-effect")
    protected String cdsEffect;
    @XmlAttribute(name = "depth")
    protected Short depth;
    @XmlAttribute(name = "functional-effect")
    protected String functionalEffect;
    @XmlAttribute(name = "gene")
    protected String gene;
    @XmlAttribute(name = "percent-reads")
    protected Float percentReads;
    @XmlAttribute(name = "position")
    protected String position;
    @XmlAttribute(name = "protein-effect")
    protected String proteinEffect;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "strand")
    protected String strand;
    @XmlAttribute(name = "transcript")
    protected String transcript;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the cdsEffect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdsEffect() {
        return cdsEffect;
    }

    /**
     * Sets the value of the cdsEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdsEffect(String value) {
        this.cdsEffect = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDepth(Short value) {
        this.depth = value;
    }

    /**
     * Gets the value of the functionalEffect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalEffect() {
        return functionalEffect;
    }

    /**
     * Sets the value of the functionalEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalEffect(String value) {
        this.functionalEffect = value;
    }

    /**
     * Gets the value of the gene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGene() {
        return gene;
    }

    /**
     * Sets the value of the gene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGene(String value) {
        this.gene = value;
    }

    /**
     * Gets the value of the percentReads property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPercentReads() {
        return percentReads;
    }

    /**
     * Sets the value of the percentReads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPercentReads(Float value) {
        this.percentReads = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the proteinEffect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProteinEffect() {
        return proteinEffect;
    }

    /**
     * Sets the value of the proteinEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProteinEffect(String value) {
        this.proteinEffect = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the strand property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public String getStrand() {
        return strand;
    }

    /**
     * Sets the value of the strand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrand(String value) {
        this.strand = value;
    }

    /**
     * Gets the value of the transcript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranscript() {
        return transcript;
    }

    /**
     * Sets the value of the transcript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranscript(String value) {
        this.transcript = value;
    }

}
