package org.mskcc.cbio.importer.cvr.darwin.dao;

import org.mskcc.cbio.importer.cvr.darwin.model.PathologyData;

public interface PathologyDAO {
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATH_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insert(PathologyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATH_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insertSelective(PathologyData record);

}