package org.mskcc.cbio.importer.cvr.darwin.dao;

import org.mskcc.cbio.importer.cvr.darwin.model.Patient;

public interface PatientDAO {
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insertSelective(Patient record);

}