package org.mskcc.cbio.importer.cvr.darwin.dao;

import org.mskcc.cbio.importer.cvr.darwin.model.SequenomResult;

public interface SequenomResultMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insert(SequenomResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Tue Nov 18 23:34:29 EST 2014
     */
    int insertSelective(SequenomResult record);

}