package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class Icd9DxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Icd9DxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDIsNull() {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDIsNotNull() {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDEqualTo(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID =", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDNotEqualTo(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID <>", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDGreaterThan(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID >", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID >=", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDLessThan(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID <", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID <=", value, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDIn(List<Integer> values) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID in", values, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDNotIn(List<Integer> values) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID not in", values, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID between", value1, value2, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_DEIDENTIFICATION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_PT_DEIDENTIFICATION_ID not between", value1, value2, "ICD9_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEIsNull() {
            addCriterion("ICD9_CODE is null");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEIsNotNull() {
            addCriterion("ICD9_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEEqualTo(String value) {
            addCriterion("ICD9_CODE =", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODENotEqualTo(String value) {
            addCriterion("ICD9_CODE <>", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEGreaterThan(String value) {
            addCriterion("ICD9_CODE >", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_CODE >=", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODELessThan(String value) {
            addCriterion("ICD9_CODE <", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODELessThanOrEqualTo(String value) {
            addCriterion("ICD9_CODE <=", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODELike(String value) {
            addCriterion("ICD9_CODE like", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODENotLike(String value) {
            addCriterion("ICD9_CODE not like", value, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEIn(List<String> values) {
            addCriterion("ICD9_CODE in", values, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODENotIn(List<String> values) {
            addCriterion("ICD9_CODE not in", values, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODEBetween(String value1, String value2) {
            addCriterion("ICD9_CODE between", value1, value2, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_CODENotBetween(String value1, String value2) {
            addCriterion("ICD9_CODE not between", value1, value2, "ICD9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCIsNull() {
            addCriterion("ICD9_DESC is null");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCIsNotNull() {
            addCriterion("ICD9_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCEqualTo(String value) {
            addCriterion("ICD9_DESC =", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCNotEqualTo(String value) {
            addCriterion("ICD9_DESC <>", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCGreaterThan(String value) {
            addCriterion("ICD9_DESC >", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_DESC >=", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCLessThan(String value) {
            addCriterion("ICD9_DESC <", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCLessThanOrEqualTo(String value) {
            addCriterion("ICD9_DESC <=", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCLike(String value) {
            addCriterion("ICD9_DESC like", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCNotLike(String value) {
            addCriterion("ICD9_DESC not like", value, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCIn(List<String> values) {
            addCriterion("ICD9_DESC in", values, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCNotIn(List<String> values) {
            addCriterion("ICD9_DESC not in", values, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCBetween(String value1, String value2) {
            addCriterion("ICD9_DESC between", value1, value2, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_DESCNotBetween(String value1, String value2) {
            addCriterion("ICD9_DESC not between", value1, value2, "ICD9_DESC");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARIsNull() {
            addCriterion("ICD9_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARIsNotNull() {
            addCriterion("ICD9_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_YEAREqualTo(Short value) {
            addCriterion("ICD9_YEAR =", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARNotEqualTo(Short value) {
            addCriterion("ICD9_YEAR <>", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARGreaterThan(Short value) {
            addCriterion("ICD9_YEAR >", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("ICD9_YEAR >=", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARLessThan(Short value) {
            addCriterion("ICD9_YEAR <", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARLessThanOrEqualTo(Short value) {
            addCriterion("ICD9_YEAR <=", value, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARIn(List<Short> values) {
            addCriterion("ICD9_YEAR in", values, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARNotIn(List<Short> values) {
            addCriterion("ICD9_YEAR not in", values, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARBetween(Short value1, Short value2) {
            addCriterion("ICD9_YEAR between", value1, value2, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARNotBetween(Short value1, Short value2) {
            addCriterion("ICD9_YEAR not between", value1, value2, "ICD9_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEIsNull() {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE is null");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEIsNotNull() {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEEqualTo(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE =", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTENotEqualTo(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE <>", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEGreaterThan(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE >", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEGreaterThanOrEqualTo(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE >=", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTELessThan(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE <", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTELessThanOrEqualTo(Integer value) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE <=", value, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEIn(List<Integer> values) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE in", values, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTENotIn(List<Integer> values) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE not in", values, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTEBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE between", value1, value2, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_DAYS_SINCE_MRN_CREATE_DTENotBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_DAYS_SINCE_MRN_CREATE_DTE not between", value1, value2, "ICD9_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHIsNull() {
            addCriterion("ICD9_YEARS_SINCE_BIRTH is null");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHIsNotNull() {
            addCriterion("ICD9_YEARS_SINCE_BIRTH is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHEqualTo(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH =", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHNotEqualTo(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH <>", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHGreaterThan(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH >", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHGreaterThanOrEqualTo(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH >=", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHLessThan(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH <", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHLessThanOrEqualTo(Integer value) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH <=", value, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHIn(List<Integer> values) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH in", values, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHNotIn(List<Integer> values) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH not in", values, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH between", value1, value2, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_YEARS_SINCE_BIRTHNotBetween(Integer value1, Integer value2) {
            addCriterion("ICD9_YEARS_SINCE_BIRTH not between", value1, value2, "ICD9_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEIsNull() {
            addCriterion("ICD9_DT_DAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEIsNotNull() {
            addCriterion("ICD9_DT_DAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEEqualTo(String value) {
            addCriterion("ICD9_DT_DAY_NAME =", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMENotEqualTo(String value) {
            addCriterion("ICD9_DT_DAY_NAME <>", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEGreaterThan(String value) {
            addCriterion("ICD9_DT_DAY_NAME >", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_DT_DAY_NAME >=", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMELessThan(String value) {
            addCriterion("ICD9_DT_DAY_NAME <", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMELessThanOrEqualTo(String value) {
            addCriterion("ICD9_DT_DAY_NAME <=", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMELike(String value) {
            addCriterion("ICD9_DT_DAY_NAME like", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMENotLike(String value) {
            addCriterion("ICD9_DT_DAY_NAME not like", value, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEIn(List<String> values) {
            addCriterion("ICD9_DT_DAY_NAME in", values, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMENotIn(List<String> values) {
            addCriterion("ICD9_DT_DAY_NAME not in", values, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMEBetween(String value1, String value2) {
            addCriterion("ICD9_DT_DAY_NAME between", value1, value2, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_DAY_NAMENotBetween(String value1, String value2) {
            addCriterion("ICD9_DT_DAY_NAME not between", value1, value2, "ICD9_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGIsNull() {
            addCriterion("ICD9_DT_WEEKDAY_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGIsNotNull() {
            addCriterion("ICD9_DT_WEEKDAY_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGEqualTo(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG =", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGNotEqualTo(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG <>", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGGreaterThan(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG >", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG >=", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGLessThan(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG <", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGLessThanOrEqualTo(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG <=", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGLike(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG like", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGNotLike(String value) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG not like", value, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGIn(List<String> values) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG in", values, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGNotIn(List<String> values) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG not in", values, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGBetween(String value1, String value2) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG between", value1, value2, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_DT_WEEKDAY_FLAGNotBetween(String value1, String value2) {
            addCriterion("ICD9_DT_WEEKDAY_FLAG not between", value1, value2, "ICD9_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEIsNull() {
            addCriterion("ICD9_MONTH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEIsNotNull() {
            addCriterion("ICD9_MONTH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEEqualTo(String value) {
            addCriterion("ICD9_MONTH_NAME =", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMENotEqualTo(String value) {
            addCriterion("ICD9_MONTH_NAME <>", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEGreaterThan(String value) {
            addCriterion("ICD9_MONTH_NAME >", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_MONTH_NAME >=", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMELessThan(String value) {
            addCriterion("ICD9_MONTH_NAME <", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMELessThanOrEqualTo(String value) {
            addCriterion("ICD9_MONTH_NAME <=", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMELike(String value) {
            addCriterion("ICD9_MONTH_NAME like", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMENotLike(String value) {
            addCriterion("ICD9_MONTH_NAME not like", value, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEIn(List<String> values) {
            addCriterion("ICD9_MONTH_NAME in", values, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMENotIn(List<String> values) {
            addCriterion("ICD9_MONTH_NAME not in", values, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMEBetween(String value1, String value2) {
            addCriterion("ICD9_MONTH_NAME between", value1, value2, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_MONTH_NAMENotBetween(String value1, String value2) {
            addCriterion("ICD9_MONTH_NAME not between", value1, value2, "ICD9_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIsNull() {
            addCriterion("ICD9_METS_IND is null");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIsNotNull() {
            addCriterion("ICD9_METS_IND is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDEqualTo(String value) {
            addCriterion("ICD9_METS_IND =", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotEqualTo(String value) {
            addCriterion("ICD9_METS_IND <>", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDGreaterThan(String value) {
            addCriterion("ICD9_METS_IND >", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_METS_IND >=", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLessThan(String value) {
            addCriterion("ICD9_METS_IND <", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLessThanOrEqualTo(String value) {
            addCriterion("ICD9_METS_IND <=", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLike(String value) {
            addCriterion("ICD9_METS_IND like", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotLike(String value) {
            addCriterion("ICD9_METS_IND not like", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIn(List<String> values) {
            addCriterion("ICD9_METS_IND in", values, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotIn(List<String> values) {
            addCriterion("ICD9_METS_IND not in", values, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDBetween(String value1, String value2) {
            addCriterion("ICD9_METS_IND between", value1, value2, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotBetween(String value1, String value2) {
            addCriterion("ICD9_METS_IND not between", value1, value2, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEIsNull() {
            addCriterion("ICD9_PT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEIsNotNull() {
            addCriterion("ICD9_PT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEEqualTo(String value) {
            addCriterion("ICD9_PT_TYPE =", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPENotEqualTo(String value) {
            addCriterion("ICD9_PT_TYPE <>", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEGreaterThan(String value) {
            addCriterion("ICD9_PT_TYPE >", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_PT_TYPE >=", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPELessThan(String value) {
            addCriterion("ICD9_PT_TYPE <", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPELessThanOrEqualTo(String value) {
            addCriterion("ICD9_PT_TYPE <=", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPELike(String value) {
            addCriterion("ICD9_PT_TYPE like", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPENotLike(String value) {
            addCriterion("ICD9_PT_TYPE not like", value, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEIn(List<String> values) {
            addCriterion("ICD9_PT_TYPE in", values, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPENotIn(List<String> values) {
            addCriterion("ICD9_PT_TYPE not in", values, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPEBetween(String value1, String value2) {
            addCriterion("ICD9_PT_TYPE between", value1, value2, "ICD9_PT_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD9_PT_TYPENotBetween(String value1, String value2) {
            addCriterion("ICD9_PT_TYPE not between", value1, value2, "ICD9_PT_TYPE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_DX_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}