package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

public class PathologyData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PATH_PT_DEIDENTIFICATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PATH_RPT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_TYPE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PATH_RPT_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_REPORT_TXT
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PATH_REPORT_TXT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PATH_DAYS_SINCE_MRN_CREATE_DTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PATH_RPT_YEARS_SINCE_BIRTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PATH_RPT_DT_DAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PATH_RPT_DT_WEEKDAY_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short PATH_RPT_MONTH_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATH_V.PATH_RPT_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PATH_RPT_YEAR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_PT_DEIDENTIFICATION_ID
     *
     * @return the value of DVCBIO.PATH_V.PATH_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPATH_PT_DEIDENTIFICATION_ID() {
        return PATH_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_PT_DEIDENTIFICATION_ID
     *
     * @param PATH_PT_DEIDENTIFICATION_ID the value for DVCBIO.PATH_V.PATH_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_PT_DEIDENTIFICATION_ID(Integer PATH_PT_DEIDENTIFICATION_ID) {
        this.PATH_PT_DEIDENTIFICATION_ID = PATH_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_ID
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPATH_RPT_ID() {
        return PATH_RPT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_ID
     *
     * @param PATH_RPT_ID the value for DVCBIO.PATH_V.PATH_RPT_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_ID(Integer PATH_RPT_ID) {
        this.PATH_RPT_ID = PATH_RPT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_TYPE
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_TYPE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPATH_RPT_TYPE() {
        return PATH_RPT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_TYPE
     *
     * @param PATH_RPT_TYPE the value for DVCBIO.PATH_V.PATH_RPT_TYPE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_TYPE(String PATH_RPT_TYPE) {
        this.PATH_RPT_TYPE = PATH_RPT_TYPE == null ? null : PATH_RPT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_REPORT_TXT
     *
     * @return the value of DVCBIO.PATH_V.PATH_REPORT_TXT
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPATH_REPORT_TXT() {
        return PATH_REPORT_TXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_REPORT_TXT
     *
     * @param PATH_REPORT_TXT the value for DVCBIO.PATH_V.PATH_REPORT_TXT
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_REPORT_TXT(Integer PATH_REPORT_TXT) {
        this.PATH_REPORT_TXT = PATH_REPORT_TXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @return the value of DVCBIO.PATH_V.PATH_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPATH_DAYS_SINCE_MRN_CREATE_DTE() {
        return PATH_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @param PATH_DAYS_SINCE_MRN_CREATE_DTE the value for DVCBIO.PATH_V.PATH_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_DAYS_SINCE_MRN_CREATE_DTE(Integer PATH_DAYS_SINCE_MRN_CREATE_DTE) {
        this.PATH_DAYS_SINCE_MRN_CREATE_DTE = PATH_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_YEARS_SINCE_BIRTH
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPATH_RPT_YEARS_SINCE_BIRTH() {
        return PATH_RPT_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_YEARS_SINCE_BIRTH
     *
     * @param PATH_RPT_YEARS_SINCE_BIRTH the value for DVCBIO.PATH_V.PATH_RPT_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_YEARS_SINCE_BIRTH(String PATH_RPT_YEARS_SINCE_BIRTH) {
        this.PATH_RPT_YEARS_SINCE_BIRTH = PATH_RPT_YEARS_SINCE_BIRTH == null ? null : PATH_RPT_YEARS_SINCE_BIRTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_DT_DAY_NAME
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPATH_RPT_DT_DAY_NAME() {
        return PATH_RPT_DT_DAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_DT_DAY_NAME
     *
     * @param PATH_RPT_DT_DAY_NAME the value for DVCBIO.PATH_V.PATH_RPT_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_DT_DAY_NAME(String PATH_RPT_DT_DAY_NAME) {
        this.PATH_RPT_DT_DAY_NAME = PATH_RPT_DT_DAY_NAME == null ? null : PATH_RPT_DT_DAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_DT_WEEKDAY_FLAG
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPATH_RPT_DT_WEEKDAY_FLAG() {
        return PATH_RPT_DT_WEEKDAY_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_DT_WEEKDAY_FLAG
     *
     * @param PATH_RPT_DT_WEEKDAY_FLAG the value for DVCBIO.PATH_V.PATH_RPT_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_DT_WEEKDAY_FLAG(String PATH_RPT_DT_WEEKDAY_FLAG) {
        this.PATH_RPT_DT_WEEKDAY_FLAG = PATH_RPT_DT_WEEKDAY_FLAG == null ? null : PATH_RPT_DT_WEEKDAY_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_MONTH_NAME
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getPATH_RPT_MONTH_NAME() {
        return PATH_RPT_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_MONTH_NAME
     *
     * @param PATH_RPT_MONTH_NAME the value for DVCBIO.PATH_V.PATH_RPT_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_MONTH_NAME(Short PATH_RPT_MONTH_NAME) {
        this.PATH_RPT_MONTH_NAME = PATH_RPT_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATH_V.PATH_RPT_YEAR
     *
     * @return the value of DVCBIO.PATH_V.PATH_RPT_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPATH_RPT_YEAR() {
        return PATH_RPT_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATH_V.PATH_RPT_YEAR
     *
     * @param PATH_RPT_YEAR the value for DVCBIO.PATH_V.PATH_RPT_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPATH_RPT_YEAR(String PATH_RPT_YEAR) {
        this.PATH_RPT_YEAR = PATH_RPT_YEAR == null ? null : PATH_RPT_YEAR.trim();
    }
}