package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class PatientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public PatientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDIsNull() {
            addCriterion("PT_PT_DEIDENTIFICATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDIsNotNull() {
            addCriterion("PT_PT_DEIDENTIFICATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDEqualTo(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID =", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDNotEqualTo(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID <>", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDGreaterThan(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID >", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID >=", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDLessThan(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID <", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID <=", value, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDIn(List<Integer> values) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID in", values, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDNotIn(List<Integer> values) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID not in", values, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDBetween(Integer value1, Integer value2) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID between", value1, value2, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_PT_DEIDENTIFICATION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("PT_PT_DEIDENTIFICATION_ID not between", value1, value2, "PT_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYIsNull() {
            addCriterion("PT_COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYIsNotNull() {
            addCriterion("PT_COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYEqualTo(String value) {
            addCriterion("PT_COUNTRY =", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYNotEqualTo(String value) {
            addCriterion("PT_COUNTRY <>", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYGreaterThan(String value) {
            addCriterion("PT_COUNTRY >", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYGreaterThanOrEqualTo(String value) {
            addCriterion("PT_COUNTRY >=", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYLessThan(String value) {
            addCriterion("PT_COUNTRY <", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYLessThanOrEqualTo(String value) {
            addCriterion("PT_COUNTRY <=", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYLike(String value) {
            addCriterion("PT_COUNTRY like", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYNotLike(String value) {
            addCriterion("PT_COUNTRY not like", value, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYIn(List<String> values) {
            addCriterion("PT_COUNTRY in", values, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYNotIn(List<String> values) {
            addCriterion("PT_COUNTRY not in", values, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYBetween(String value1, String value2) {
            addCriterion("PT_COUNTRY between", value1, value2, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_COUNTRYNotBetween(String value1, String value2) {
            addCriterion("PT_COUNTRY not between", value1, value2, "PT_COUNTRY");
            return (Criteria) this;
        }

        public Criteria andPT_STATEIsNull() {
            addCriterion("PT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPT_STATEIsNotNull() {
            addCriterion("PT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPT_STATEEqualTo(String value) {
            addCriterion("PT_STATE =", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATENotEqualTo(String value) {
            addCriterion("PT_STATE <>", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATEGreaterThan(String value) {
            addCriterion("PT_STATE >", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATEGreaterThanOrEqualTo(String value) {
            addCriterion("PT_STATE >=", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATELessThan(String value) {
            addCriterion("PT_STATE <", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATELessThanOrEqualTo(String value) {
            addCriterion("PT_STATE <=", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATELike(String value) {
            addCriterion("PT_STATE like", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATENotLike(String value) {
            addCriterion("PT_STATE not like", value, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATEIn(List<String> values) {
            addCriterion("PT_STATE in", values, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATENotIn(List<String> values) {
            addCriterion("PT_STATE not in", values, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATEBetween(String value1, String value2) {
            addCriterion("PT_STATE between", value1, value2, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_STATENotBetween(String value1, String value2) {
            addCriterion("PT_STATE not between", value1, value2, "PT_STATE");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDIsNull() {
            addCriterion("PT_ZIP3_CD is null");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDIsNotNull() {
            addCriterion("PT_ZIP3_CD is not null");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDEqualTo(String value) {
            addCriterion("PT_ZIP3_CD =", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDNotEqualTo(String value) {
            addCriterion("PT_ZIP3_CD <>", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDGreaterThan(String value) {
            addCriterion("PT_ZIP3_CD >", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDGreaterThanOrEqualTo(String value) {
            addCriterion("PT_ZIP3_CD >=", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDLessThan(String value) {
            addCriterion("PT_ZIP3_CD <", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDLessThanOrEqualTo(String value) {
            addCriterion("PT_ZIP3_CD <=", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDLike(String value) {
            addCriterion("PT_ZIP3_CD like", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDNotLike(String value) {
            addCriterion("PT_ZIP3_CD not like", value, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDIn(List<String> values) {
            addCriterion("PT_ZIP3_CD in", values, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDNotIn(List<String> values) {
            addCriterion("PT_ZIP3_CD not in", values, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDBetween(String value1, String value2) {
            addCriterion("PT_ZIP3_CD between", value1, value2, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_ZIP3_CDNotBetween(String value1, String value2) {
            addCriterion("PT_ZIP3_CD not between", value1, value2, "PT_ZIP3_CD");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARIsNull() {
            addCriterion("PT_BIRTH_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARIsNotNull() {
            addCriterion("PT_BIRTH_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEAREqualTo(Short value) {
            addCriterion("PT_BIRTH_YEAR =", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARNotEqualTo(Short value) {
            addCriterion("PT_BIRTH_YEAR <>", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARGreaterThan(Short value) {
            addCriterion("PT_BIRTH_YEAR >", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("PT_BIRTH_YEAR >=", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARLessThan(Short value) {
            addCriterion("PT_BIRTH_YEAR <", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARLessThanOrEqualTo(Short value) {
            addCriterion("PT_BIRTH_YEAR <=", value, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARIn(List<Short> values) {
            addCriterion("PT_BIRTH_YEAR in", values, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARNotIn(List<Short> values) {
            addCriterion("PT_BIRTH_YEAR not in", values, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARBetween(Short value1, Short value2) {
            addCriterion("PT_BIRTH_YEAR between", value1, value2, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_YEARNotBetween(Short value1, Short value2) {
            addCriterion("PT_BIRTH_YEAR not between", value1, value2, "PT_BIRTH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERIsNull() {
            addCriterion("PT_BIRTH_QUARTER is null");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERIsNotNull() {
            addCriterion("PT_BIRTH_QUARTER is not null");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTEREqualTo(Short value) {
            addCriterion("PT_BIRTH_QUARTER =", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERNotEqualTo(Short value) {
            addCriterion("PT_BIRTH_QUARTER <>", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERGreaterThan(Short value) {
            addCriterion("PT_BIRTH_QUARTER >", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERGreaterThanOrEqualTo(Short value) {
            addCriterion("PT_BIRTH_QUARTER >=", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERLessThan(Short value) {
            addCriterion("PT_BIRTH_QUARTER <", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERLessThanOrEqualTo(Short value) {
            addCriterion("PT_BIRTH_QUARTER <=", value, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERIn(List<Short> values) {
            addCriterion("PT_BIRTH_QUARTER in", values, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERNotIn(List<Short> values) {
            addCriterion("PT_BIRTH_QUARTER not in", values, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERBetween(Short value1, Short value2) {
            addCriterion("PT_BIRTH_QUARTER between", value1, value2, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_BIRTH_QUARTERNotBetween(Short value1, Short value2) {
            addCriterion("PT_BIRTH_QUARTER not between", value1, value2, "PT_BIRTH_QUARTER");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCIsNull() {
            addCriterion("PT_SEX_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCIsNotNull() {
            addCriterion("PT_SEX_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCEqualTo(String value) {
            addCriterion("PT_SEX_DESC =", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCNotEqualTo(String value) {
            addCriterion("PT_SEX_DESC <>", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCGreaterThan(String value) {
            addCriterion("PT_SEX_DESC >", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("PT_SEX_DESC >=", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCLessThan(String value) {
            addCriterion("PT_SEX_DESC <", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCLessThanOrEqualTo(String value) {
            addCriterion("PT_SEX_DESC <=", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCLike(String value) {
            addCriterion("PT_SEX_DESC like", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCNotLike(String value) {
            addCriterion("PT_SEX_DESC not like", value, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCIn(List<String> values) {
            addCriterion("PT_SEX_DESC in", values, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCNotIn(List<String> values) {
            addCriterion("PT_SEX_DESC not in", values, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCBetween(String value1, String value2) {
            addCriterion("PT_SEX_DESC between", value1, value2, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_SEX_DESCNotBetween(String value1, String value2) {
            addCriterion("PT_SEX_DESC not between", value1, value2, "PT_SEX_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCIsNull() {
            addCriterion("PT_RACE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCIsNotNull() {
            addCriterion("PT_RACE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCEqualTo(String value) {
            addCriterion("PT_RACE_DESC =", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCNotEqualTo(String value) {
            addCriterion("PT_RACE_DESC <>", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCGreaterThan(String value) {
            addCriterion("PT_RACE_DESC >", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("PT_RACE_DESC >=", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCLessThan(String value) {
            addCriterion("PT_RACE_DESC <", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCLessThanOrEqualTo(String value) {
            addCriterion("PT_RACE_DESC <=", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCLike(String value) {
            addCriterion("PT_RACE_DESC like", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCNotLike(String value) {
            addCriterion("PT_RACE_DESC not like", value, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCIn(List<String> values) {
            addCriterion("PT_RACE_DESC in", values, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCNotIn(List<String> values) {
            addCriterion("PT_RACE_DESC not in", values, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCBetween(String value1, String value2) {
            addCriterion("PT_RACE_DESC between", value1, value2, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RACE_DESCNotBetween(String value1, String value2) {
            addCriterion("PT_RACE_DESC not between", value1, value2, "PT_RACE_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSIsNull() {
            addCriterion("PT_VITAL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSIsNotNull() {
            addCriterion("PT_VITAL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSEqualTo(String value) {
            addCriterion("PT_VITAL_STATUS =", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSNotEqualTo(String value) {
            addCriterion("PT_VITAL_STATUS <>", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSGreaterThan(String value) {
            addCriterion("PT_VITAL_STATUS >", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSGreaterThanOrEqualTo(String value) {
            addCriterion("PT_VITAL_STATUS >=", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSLessThan(String value) {
            addCriterion("PT_VITAL_STATUS <", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSLessThanOrEqualTo(String value) {
            addCriterion("PT_VITAL_STATUS <=", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSLike(String value) {
            addCriterion("PT_VITAL_STATUS like", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSNotLike(String value) {
            addCriterion("PT_VITAL_STATUS not like", value, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSIn(List<String> values) {
            addCriterion("PT_VITAL_STATUS in", values, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSNotIn(List<String> values) {
            addCriterion("PT_VITAL_STATUS not in", values, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSBetween(String value1, String value2) {
            addCriterion("PT_VITAL_STATUS between", value1, value2, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_VITAL_STATUSNotBetween(String value1, String value2) {
            addCriterion("PT_VITAL_STATUS not between", value1, value2, "PT_VITAL_STATUS");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCIsNull() {
            addCriterion("PT_MARITAL_STS_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCIsNotNull() {
            addCriterion("PT_MARITAL_STS_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCEqualTo(String value) {
            addCriterion("PT_MARITAL_STS_DESC =", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCNotEqualTo(String value) {
            addCriterion("PT_MARITAL_STS_DESC <>", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCGreaterThan(String value) {
            addCriterion("PT_MARITAL_STS_DESC >", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("PT_MARITAL_STS_DESC >=", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCLessThan(String value) {
            addCriterion("PT_MARITAL_STS_DESC <", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCLessThanOrEqualTo(String value) {
            addCriterion("PT_MARITAL_STS_DESC <=", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCLike(String value) {
            addCriterion("PT_MARITAL_STS_DESC like", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCNotLike(String value) {
            addCriterion("PT_MARITAL_STS_DESC not like", value, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCIn(List<String> values) {
            addCriterion("PT_MARITAL_STS_DESC in", values, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCNotIn(List<String> values) {
            addCriterion("PT_MARITAL_STS_DESC not in", values, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCBetween(String value1, String value2) {
            addCriterion("PT_MARITAL_STS_DESC between", value1, value2, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_MARITAL_STS_DESCNotBetween(String value1, String value2) {
            addCriterion("PT_MARITAL_STS_DESC not between", value1, value2, "PT_MARITAL_STS_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCIsNull() {
            addCriterion("PT_RELIGION_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCIsNotNull() {
            addCriterion("PT_RELIGION_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCEqualTo(String value) {
            addCriterion("PT_RELIGION_DESC =", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCNotEqualTo(String value) {
            addCriterion("PT_RELIGION_DESC <>", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCGreaterThan(String value) {
            addCriterion("PT_RELIGION_DESC >", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("PT_RELIGION_DESC >=", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCLessThan(String value) {
            addCriterion("PT_RELIGION_DESC <", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCLessThanOrEqualTo(String value) {
            addCriterion("PT_RELIGION_DESC <=", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCLike(String value) {
            addCriterion("PT_RELIGION_DESC like", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCNotLike(String value) {
            addCriterion("PT_RELIGION_DESC not like", value, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCIn(List<String> values) {
            addCriterion("PT_RELIGION_DESC in", values, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCNotIn(List<String> values) {
            addCriterion("PT_RELIGION_DESC not in", values, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCBetween(String value1, String value2) {
            addCriterion("PT_RELIGION_DESC between", value1, value2, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_RELIGION_DESCNotBetween(String value1, String value2) {
            addCriterion("PT_RELIGION_DESC not between", value1, value2, "PT_RELIGION_DESC");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARIsNull() {
            addCriterion("PT_DEATH_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARIsNotNull() {
            addCriterion("PT_DEATH_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEAREqualTo(Short value) {
            addCriterion("PT_DEATH_YEAR =", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARNotEqualTo(Short value) {
            addCriterion("PT_DEATH_YEAR <>", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARGreaterThan(Short value) {
            addCriterion("PT_DEATH_YEAR >", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("PT_DEATH_YEAR >=", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARLessThan(Short value) {
            addCriterion("PT_DEATH_YEAR <", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARLessThanOrEqualTo(Short value) {
            addCriterion("PT_DEATH_YEAR <=", value, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARIn(List<Short> values) {
            addCriterion("PT_DEATH_YEAR in", values, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARNotIn(List<Short> values) {
            addCriterion("PT_DEATH_YEAR not in", values, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARBetween(Short value1, Short value2) {
            addCriterion("PT_DEATH_YEAR between", value1, value2, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_DEATH_YEARNotBetween(Short value1, Short value2) {
            addCriterion("PT_DEATH_YEAR not between", value1, value2, "PT_DEATH_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARIsNull() {
            addCriterion("PT_MRN_CREATE_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARIsNotNull() {
            addCriterion("PT_MRN_CREATE_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEAREqualTo(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR =", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARNotEqualTo(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR <>", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARGreaterThan(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR >", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR >=", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARLessThan(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR <", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARLessThanOrEqualTo(Short value) {
            addCriterion("PT_MRN_CREATE_YEAR <=", value, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARIn(List<Short> values) {
            addCriterion("PT_MRN_CREATE_YEAR in", values, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARNotIn(List<Short> values) {
            addCriterion("PT_MRN_CREATE_YEAR not in", values, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARBetween(Short value1, Short value2) {
            addCriterion("PT_MRN_CREATE_YEAR between", value1, value2, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }

        public Criteria andPT_MRN_CREATE_YEARNotBetween(Short value1, Short value2) {
            addCriterion("PT_MRN_CREATE_YEAR not between", value1, value2, "PT_MRN_CREATE_YEAR");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.PATIENT_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}