package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

public class Procedure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PROC_PT_DEIDENTIFICATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_CPT_CD
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_CPT_CD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_CPT_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_CPT_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_ADDITIONAL_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_ADDITIONAL_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_SERVICE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_SERVICE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_INOUT_PT_IND
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_INOUT_PT_IND;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PROC_DAYS_SINCE_MRN_CREATE_DTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer PROC_YEARS_SINCE_BIRTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_DT_DAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_DT_WEEKDAY_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String PROC_MONTH_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PROCEDURES_V.PROC_YEAR)
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short PROC_YEAR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_PT_DEIDENTIFICATION_ID
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPROC_PT_DEIDENTIFICATION_ID() {
        return PROC_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_PT_DEIDENTIFICATION_ID
     *
     * @param PROC_PT_DEIDENTIFICATION_ID the value for DVCBIO.PROCEDURES_V.PROC_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_PT_DEIDENTIFICATION_ID(Integer PROC_PT_DEIDENTIFICATION_ID) {
        this.PROC_PT_DEIDENTIFICATION_ID = PROC_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_CPT_CD
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_CPT_CD
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_CPT_CD() {
        return PROC_CPT_CD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_CPT_CD
     *
     * @param PROC_CPT_CD the value for DVCBIO.PROCEDURES_V.PROC_CPT_CD
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_CPT_CD(String PROC_CPT_CD) {
        this.PROC_CPT_CD = PROC_CPT_CD == null ? null : PROC_CPT_CD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_CPT_DESC
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_CPT_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_CPT_DESC() {
        return PROC_CPT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_CPT_DESC
     *
     * @param PROC_CPT_DESC the value for DVCBIO.PROCEDURES_V.PROC_CPT_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_CPT_DESC(String PROC_CPT_DESC) {
        this.PROC_CPT_DESC = PROC_CPT_DESC == null ? null : PROC_CPT_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_ADDITIONAL_DESC
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_ADDITIONAL_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_ADDITIONAL_DESC() {
        return PROC_ADDITIONAL_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_ADDITIONAL_DESC
     *
     * @param PROC_ADDITIONAL_DESC the value for DVCBIO.PROCEDURES_V.PROC_ADDITIONAL_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_ADDITIONAL_DESC(String PROC_ADDITIONAL_DESC) {
        this.PROC_ADDITIONAL_DESC = PROC_ADDITIONAL_DESC == null ? null : PROC_ADDITIONAL_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_SERVICE
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_SERVICE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_SERVICE() {
        return PROC_SERVICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_SERVICE
     *
     * @param PROC_SERVICE the value for DVCBIO.PROCEDURES_V.PROC_SERVICE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_SERVICE(String PROC_SERVICE) {
        this.PROC_SERVICE = PROC_SERVICE == null ? null : PROC_SERVICE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_INOUT_PT_IND
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_INOUT_PT_IND
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_INOUT_PT_IND() {
        return PROC_INOUT_PT_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_INOUT_PT_IND
     *
     * @param PROC_INOUT_PT_IND the value for DVCBIO.PROCEDURES_V.PROC_INOUT_PT_IND
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_INOUT_PT_IND(String PROC_INOUT_PT_IND) {
        this.PROC_INOUT_PT_IND = PROC_INOUT_PT_IND == null ? null : PROC_INOUT_PT_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPROC_DAYS_SINCE_MRN_CREATE_DTE() {
        return PROC_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @param PROC_DAYS_SINCE_MRN_CREATE_DTE the value for DVCBIO.PROCEDURES_V.PROC_DAYS_SINCE_MRN_CREATE_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_DAYS_SINCE_MRN_CREATE_DTE(Integer PROC_DAYS_SINCE_MRN_CREATE_DTE) {
        this.PROC_DAYS_SINCE_MRN_CREATE_DTE = PROC_DAYS_SINCE_MRN_CREATE_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_YEARS_SINCE_BIRTH
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getPROC_YEARS_SINCE_BIRTH() {
        return PROC_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_YEARS_SINCE_BIRTH
     *
     * @param PROC_YEARS_SINCE_BIRTH the value for DVCBIO.PROCEDURES_V.PROC_YEARS_SINCE_BIRTH
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_YEARS_SINCE_BIRTH(Integer PROC_YEARS_SINCE_BIRTH) {
        this.PROC_YEARS_SINCE_BIRTH = PROC_YEARS_SINCE_BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_DT_DAY_NAME
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_DT_DAY_NAME() {
        return PROC_DT_DAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_DT_DAY_NAME
     *
     * @param PROC_DT_DAY_NAME the value for DVCBIO.PROCEDURES_V.PROC_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_DT_DAY_NAME(String PROC_DT_DAY_NAME) {
        this.PROC_DT_DAY_NAME = PROC_DT_DAY_NAME == null ? null : PROC_DT_DAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_DT_WEEKDAY_FLAG
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_DT_WEEKDAY_FLAG() {
        return PROC_DT_WEEKDAY_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_DT_WEEKDAY_FLAG
     *
     * @param PROC_DT_WEEKDAY_FLAG the value for DVCBIO.PROCEDURES_V.PROC_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_DT_WEEKDAY_FLAG(String PROC_DT_WEEKDAY_FLAG) {
        this.PROC_DT_WEEKDAY_FLAG = PROC_DT_WEEKDAY_FLAG == null ? null : PROC_DT_WEEKDAY_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_MONTH_NAME
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getPROC_MONTH_NAME() {
        return PROC_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_MONTH_NAME
     *
     * @param PROC_MONTH_NAME the value for DVCBIO.PROCEDURES_V.PROC_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_MONTH_NAME(String PROC_MONTH_NAME) {
        this.PROC_MONTH_NAME = PROC_MONTH_NAME == null ? null : PROC_MONTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PROCEDURES_V.PROC_YEAR)
     *
     * @return the value of DVCBIO.PROCEDURES_V.PROC_YEAR)
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getPROC_YEAR() {
        return PROC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PROCEDURES_V.PROC_YEAR)
     *
     * @param PROC_YEAR) the value for DVCBIO.PROCEDURES_V.PROC_YEAR)
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setPROC_YEAR(Short PROC_YEAR) {
        this.PROC_YEAR = PROC_YEAR;
    }
}