package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class SequenomResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public SequenomResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDIsNull() {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDIsNotNull() {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDEqualTo(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID =", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDNotEqualTo(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID <>", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDGreaterThan(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID >", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID >=", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDLessThan(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID <", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID <=", value, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDIn(List<Integer> values) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID in", values, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDNotIn(List<Integer> values) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID not in", values, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID between", value1, value2, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_PT_DEIDENTIFICATION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_PT_DEIDENTIFICATION_ID not between", value1, value2, "SEQ_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEIsNull() {
            addCriterion("SEQ_GENE is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEIsNotNull() {
            addCriterion("SEQ_GENE is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEEqualTo(String value) {
            addCriterion("SEQ_GENE =", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENENotEqualTo(String value) {
            addCriterion("SEQ_GENE <>", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEGreaterThan(String value) {
            addCriterion("SEQ_GENE >", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_GENE >=", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENELessThan(String value) {
            addCriterion("SEQ_GENE <", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENELessThanOrEqualTo(String value) {
            addCriterion("SEQ_GENE <=", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENELike(String value) {
            addCriterion("SEQ_GENE like", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENENotLike(String value) {
            addCriterion("SEQ_GENE not like", value, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEIn(List<String> values) {
            addCriterion("SEQ_GENE in", values, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENENotIn(List<String> values) {
            addCriterion("SEQ_GENE not in", values, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENEBetween(String value1, String value2) {
            addCriterion("SEQ_GENE between", value1, value2, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_GENENotBetween(String value1, String value2) {
            addCriterion("SEQ_GENE not between", value1, value2, "SEQ_GENE");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTIsNull() {
            addCriterion("SEQ_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTIsNotNull() {
            addCriterion("SEQ_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTEqualTo(String value) {
            addCriterion("SEQ_RESULT =", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTNotEqualTo(String value) {
            addCriterion("SEQ_RESULT <>", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTGreaterThan(String value) {
            addCriterion("SEQ_RESULT >", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_RESULT >=", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTLessThan(String value) {
            addCriterion("SEQ_RESULT <", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTLessThanOrEqualTo(String value) {
            addCriterion("SEQ_RESULT <=", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTLike(String value) {
            addCriterion("SEQ_RESULT like", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTNotLike(String value) {
            addCriterion("SEQ_RESULT not like", value, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTIn(List<String> values) {
            addCriterion("SEQ_RESULT in", values, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTNotIn(List<String> values) {
            addCriterion("SEQ_RESULT not in", values, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTBetween(String value1, String value2) {
            addCriterion("SEQ_RESULT between", value1, value2, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_RESULTNotBetween(String value1, String value2) {
            addCriterion("SEQ_RESULT not between", value1, value2, "SEQ_RESULT");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSIsNull() {
            addCriterion("SEQ_LOCUS is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSIsNotNull() {
            addCriterion("SEQ_LOCUS is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSEqualTo(String value) {
            addCriterion("SEQ_LOCUS =", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSNotEqualTo(String value) {
            addCriterion("SEQ_LOCUS <>", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSGreaterThan(String value) {
            addCriterion("SEQ_LOCUS >", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_LOCUS >=", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSLessThan(String value) {
            addCriterion("SEQ_LOCUS <", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSLessThanOrEqualTo(String value) {
            addCriterion("SEQ_LOCUS <=", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSLike(String value) {
            addCriterion("SEQ_LOCUS like", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSNotLike(String value) {
            addCriterion("SEQ_LOCUS not like", value, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSIn(List<String> values) {
            addCriterion("SEQ_LOCUS in", values, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSNotIn(List<String> values) {
            addCriterion("SEQ_LOCUS not in", values, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSBetween(String value1, String value2) {
            addCriterion("SEQ_LOCUS between", value1, value2, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_LOCUSNotBetween(String value1, String value2) {
            addCriterion("SEQ_LOCUS not between", value1, value2, "SEQ_LOCUS");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDIsNull() {
            addCriterion("SEQ_AMINO_ACID is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDIsNotNull() {
            addCriterion("SEQ_AMINO_ACID is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDEqualTo(String value) {
            addCriterion("SEQ_AMINO_ACID =", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDNotEqualTo(String value) {
            addCriterion("SEQ_AMINO_ACID <>", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDGreaterThan(String value) {
            addCriterion("SEQ_AMINO_ACID >", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_AMINO_ACID >=", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDLessThan(String value) {
            addCriterion("SEQ_AMINO_ACID <", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDLessThanOrEqualTo(String value) {
            addCriterion("SEQ_AMINO_ACID <=", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDLike(String value) {
            addCriterion("SEQ_AMINO_ACID like", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDNotLike(String value) {
            addCriterion("SEQ_AMINO_ACID not like", value, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDIn(List<String> values) {
            addCriterion("SEQ_AMINO_ACID in", values, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDNotIn(List<String> values) {
            addCriterion("SEQ_AMINO_ACID not in", values, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDBetween(String value1, String value2) {
            addCriterion("SEQ_AMINO_ACID between", value1, value2, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_AMINO_ACIDNotBetween(String value1, String value2) {
            addCriterion("SEQ_AMINO_ACID not between", value1, value2, "SEQ_AMINO_ACID");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEIsNull() {
            addCriterion("SEQ_NUCLEOTIDE is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEIsNotNull() {
            addCriterion("SEQ_NUCLEOTIDE is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEEqualTo(String value) {
            addCriterion("SEQ_NUCLEOTIDE =", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDENotEqualTo(String value) {
            addCriterion("SEQ_NUCLEOTIDE <>", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEGreaterThan(String value) {
            addCriterion("SEQ_NUCLEOTIDE >", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_NUCLEOTIDE >=", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDELessThan(String value) {
            addCriterion("SEQ_NUCLEOTIDE <", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDELessThanOrEqualTo(String value) {
            addCriterion("SEQ_NUCLEOTIDE <=", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDELike(String value) {
            addCriterion("SEQ_NUCLEOTIDE like", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDENotLike(String value) {
            addCriterion("SEQ_NUCLEOTIDE not like", value, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEIn(List<String> values) {
            addCriterion("SEQ_NUCLEOTIDE in", values, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDENotIn(List<String> values) {
            addCriterion("SEQ_NUCLEOTIDE not in", values, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDEBetween(String value1, String value2) {
            addCriterion("SEQ_NUCLEOTIDE between", value1, value2, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUCLEOTIDENotBetween(String value1, String value2) {
            addCriterion("SEQ_NUCLEOTIDE not between", value1, value2, "SEQ_NUCLEOTIDE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILIsNull() {
            addCriterion("SEQ_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILIsNotNull() {
            addCriterion("SEQ_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILEqualTo(String value) {
            addCriterion("SEQ_DETAIL =", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILNotEqualTo(String value) {
            addCriterion("SEQ_DETAIL <>", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILGreaterThan(String value) {
            addCriterion("SEQ_DETAIL >", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_DETAIL >=", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILLessThan(String value) {
            addCriterion("SEQ_DETAIL <", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILLessThanOrEqualTo(String value) {
            addCriterion("SEQ_DETAIL <=", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILLike(String value) {
            addCriterion("SEQ_DETAIL like", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILNotLike(String value) {
            addCriterion("SEQ_DETAIL not like", value, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILIn(List<String> values) {
            addCriterion("SEQ_DETAIL in", values, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILNotIn(List<String> values) {
            addCriterion("SEQ_DETAIL not in", values, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILBetween(String value1, String value2) {
            addCriterion("SEQ_DETAIL between", value1, value2, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_DETAILNotBetween(String value1, String value2) {
            addCriterion("SEQ_DETAIL not between", value1, value2, "SEQ_DETAIL");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEIsNull() {
            addCriterion("SEQ_ABERRATION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEIsNotNull() {
            addCriterion("SEQ_ABERRATION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEEqualTo(String value) {
            addCriterion("SEQ_ABERRATION_TYPE =", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPENotEqualTo(String value) {
            addCriterion("SEQ_ABERRATION_TYPE <>", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEGreaterThan(String value) {
            addCriterion("SEQ_ABERRATION_TYPE >", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_ABERRATION_TYPE >=", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPELessThan(String value) {
            addCriterion("SEQ_ABERRATION_TYPE <", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPELessThanOrEqualTo(String value) {
            addCriterion("SEQ_ABERRATION_TYPE <=", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPELike(String value) {
            addCriterion("SEQ_ABERRATION_TYPE like", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPENotLike(String value) {
            addCriterion("SEQ_ABERRATION_TYPE not like", value, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEIn(List<String> values) {
            addCriterion("SEQ_ABERRATION_TYPE in", values, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPENotIn(List<String> values) {
            addCriterion("SEQ_ABERRATION_TYPE not in", values, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPEBetween(String value1, String value2) {
            addCriterion("SEQ_ABERRATION_TYPE between", value1, value2, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_ABERRATION_TYPENotBetween(String value1, String value2) {
            addCriterion("SEQ_ABERRATION_TYPE not between", value1, value2, "SEQ_ABERRATION_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEIsNull() {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEIsNotNull() {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEEqualTo(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE =", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTENotEqualTo(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE <>", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEGreaterThan(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE >", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE >=", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTELessThan(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE <", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTELessThanOrEqualTo(Integer value) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE <=", value, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEIn(List<Integer> values) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE in", values, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTENotIn(List<Integer> values) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE not in", values, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTEBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE between", value1, value2, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_DAYS_SINCE_MRN_CREATE_DTENotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_DAYS_SINCE_MRN_CREATE_DTE not between", value1, value2, "SEQ_DAYS_SINCE_MRN_CREATE_DTE");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHIsNull() {
            addCriterion("SEQ_YEARS_SINCE_BIRTH is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHIsNotNull() {
            addCriterion("SEQ_YEARS_SINCE_BIRTH is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHEqualTo(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH =", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHNotEqualTo(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH <>", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHGreaterThan(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH >", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH >=", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHLessThan(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH <", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH <=", value, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHIn(List<Integer> values) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH in", values, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHNotIn(List<Integer> values) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH not in", values, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH between", value1, value2, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARS_SINCE_BIRTHNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_YEARS_SINCE_BIRTH not between", value1, value2, "SEQ_YEARS_SINCE_BIRTH");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEIsNull() {
            addCriterion("SEQ_DT_DAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEIsNotNull() {
            addCriterion("SEQ_DT_DAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEEqualTo(String value) {
            addCriterion("SEQ_DT_DAY_NAME =", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMENotEqualTo(String value) {
            addCriterion("SEQ_DT_DAY_NAME <>", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEGreaterThan(String value) {
            addCriterion("SEQ_DT_DAY_NAME >", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_DT_DAY_NAME >=", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMELessThan(String value) {
            addCriterion("SEQ_DT_DAY_NAME <", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMELessThanOrEqualTo(String value) {
            addCriterion("SEQ_DT_DAY_NAME <=", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMELike(String value) {
            addCriterion("SEQ_DT_DAY_NAME like", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMENotLike(String value) {
            addCriterion("SEQ_DT_DAY_NAME not like", value, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEIn(List<String> values) {
            addCriterion("SEQ_DT_DAY_NAME in", values, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMENotIn(List<String> values) {
            addCriterion("SEQ_DT_DAY_NAME not in", values, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMEBetween(String value1, String value2) {
            addCriterion("SEQ_DT_DAY_NAME between", value1, value2, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_DAY_NAMENotBetween(String value1, String value2) {
            addCriterion("SEQ_DT_DAY_NAME not between", value1, value2, "SEQ_DT_DAY_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGIsNull() {
            addCriterion("SEQ_DT_WEEKDAY_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGIsNotNull() {
            addCriterion("SEQ_DT_WEEKDAY_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGEqualTo(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG =", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGNotEqualTo(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG <>", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGGreaterThan(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG >", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG >=", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGLessThan(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG <", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGLessThanOrEqualTo(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG <=", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGLike(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG like", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGNotLike(String value) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG not like", value, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGIn(List<String> values) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG in", values, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGNotIn(List<String> values) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG not in", values, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGBetween(String value1, String value2) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG between", value1, value2, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_DT_WEEKDAY_FLAGNotBetween(String value1, String value2) {
            addCriterion("SEQ_DT_WEEKDAY_FLAG not between", value1, value2, "SEQ_DT_WEEKDAY_FLAG");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEIsNull() {
            addCriterion("SEQ_MONTH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEIsNotNull() {
            addCriterion("SEQ_MONTH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEEqualTo(String value) {
            addCriterion("SEQ_MONTH_NAME =", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMENotEqualTo(String value) {
            addCriterion("SEQ_MONTH_NAME <>", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEGreaterThan(String value) {
            addCriterion("SEQ_MONTH_NAME >", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_MONTH_NAME >=", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMELessThan(String value) {
            addCriterion("SEQ_MONTH_NAME <", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMELessThanOrEqualTo(String value) {
            addCriterion("SEQ_MONTH_NAME <=", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMELike(String value) {
            addCriterion("SEQ_MONTH_NAME like", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMENotLike(String value) {
            addCriterion("SEQ_MONTH_NAME not like", value, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEIn(List<String> values) {
            addCriterion("SEQ_MONTH_NAME in", values, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMENotIn(List<String> values) {
            addCriterion("SEQ_MONTH_NAME not in", values, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMEBetween(String value1, String value2) {
            addCriterion("SEQ_MONTH_NAME between", value1, value2, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_MONTH_NAMENotBetween(String value1, String value2) {
            addCriterion("SEQ_MONTH_NAME not between", value1, value2, "SEQ_MONTH_NAME");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARIsNull() {
            addCriterion("SEQ_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARIsNotNull() {
            addCriterion("SEQ_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEAREqualTo(Short value) {
            addCriterion("SEQ_YEAR =", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARNotEqualTo(Short value) {
            addCriterion("SEQ_YEAR <>", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARGreaterThan(Short value) {
            addCriterion("SEQ_YEAR >", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("SEQ_YEAR >=", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARLessThan(Short value) {
            addCriterion("SEQ_YEAR <", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARLessThanOrEqualTo(Short value) {
            addCriterion("SEQ_YEAR <=", value, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARIn(List<Short> values) {
            addCriterion("SEQ_YEAR in", values, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARNotIn(List<Short> values) {
            addCriterion("SEQ_YEAR not in", values, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARBetween(Short value1, Short value2) {
            addCriterion("SEQ_YEAR between", value1, value2, "SEQ_YEAR");
            return (Criteria) this;
        }

        public Criteria andSEQ_YEARNotBetween(Short value1, Short value2) {
            addCriterion("SEQ_YEAR not between", value1, value2, "SEQ_YEAR");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.SEQUENOM_RESULTS_V
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}