package org.mskcc.cbio.importer.cvr.darwin.model.dvcbio;

public class Tumor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer TUMOR_PT_DEIDENTIFICATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_DAYS_SINCE_FIRST_MSK_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer TUMOR_DAYS_SINCE_FIRST_MSK_DTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_DT_DAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_DT_WEEKDAY_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_MONTH_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short TUMOR_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_SEQ_NO
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short TUMOR_SEQ_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_MSK_CASE_STS
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_MSK_CASE_STS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_MSK_CLASS_OF_CASE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_MSK_CLASS_OF_CASE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_HISTOLOGY_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_HISTOLOGY_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_SITE_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_SITE_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_SITE_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_SITE_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_DX_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short TUMOR_DX_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_SURG_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Short TUMOR_SURG_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_LATERALITY
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_LATERALITY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_DX
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer TUMOR_PT_AGE_AT_DX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_SURG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private Integer TUMOR_PT_AGE_AT_SURG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_PATH_TNM_M;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_PATH_TNM_N;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_PATH_TNM_T;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_PATH_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_PATH_STG_GRP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_CLIN_TNM_M;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_CLIN_TNM_N;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_CLIN_TNM_T;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.TUMOR_V.TUMOR_CLIN_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    private String TUMOR_CLIN_STG_GRP;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_DEIDENTIFICATION_ID
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getTUMOR_PT_DEIDENTIFICATION_ID() {
        return TUMOR_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_DEIDENTIFICATION_ID
     *
     * @param TUMOR_PT_DEIDENTIFICATION_ID the value for DVCBIO.TUMOR_V.TUMOR_PT_DEIDENTIFICATION_ID
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PT_DEIDENTIFICATION_ID(Integer TUMOR_PT_DEIDENTIFICATION_ID) {
        this.TUMOR_PT_DEIDENTIFICATION_ID = TUMOR_PT_DEIDENTIFICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_DAYS_SINCE_FIRST_MSK_DTE
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_DAYS_SINCE_FIRST_MSK_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getTUMOR_DAYS_SINCE_FIRST_MSK_DTE() {
        return TUMOR_DAYS_SINCE_FIRST_MSK_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_DAYS_SINCE_FIRST_MSK_DTE
     *
     * @param TUMOR_DAYS_SINCE_FIRST_MSK_DTE the value for DVCBIO.TUMOR_V.TUMOR_DAYS_SINCE_FIRST_MSK_DTE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_DAYS_SINCE_FIRST_MSK_DTE(Integer TUMOR_DAYS_SINCE_FIRST_MSK_DTE) {
        this.TUMOR_DAYS_SINCE_FIRST_MSK_DTE = TUMOR_DAYS_SINCE_FIRST_MSK_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_DT_DAY_NAME
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_DT_DAY_NAME() {
        return TUMOR_DT_DAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_DT_DAY_NAME
     *
     * @param TUMOR_DT_DAY_NAME the value for DVCBIO.TUMOR_V.TUMOR_DT_DAY_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_DT_DAY_NAME(String TUMOR_DT_DAY_NAME) {
        this.TUMOR_DT_DAY_NAME = TUMOR_DT_DAY_NAME == null ? null : TUMOR_DT_DAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_DT_WEEKDAY_FLAG
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_DT_WEEKDAY_FLAG() {
        return TUMOR_DT_WEEKDAY_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_DT_WEEKDAY_FLAG
     *
     * @param TUMOR_DT_WEEKDAY_FLAG the value for DVCBIO.TUMOR_V.TUMOR_DT_WEEKDAY_FLAG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_DT_WEEKDAY_FLAG(String TUMOR_DT_WEEKDAY_FLAG) {
        this.TUMOR_DT_WEEKDAY_FLAG = TUMOR_DT_WEEKDAY_FLAG == null ? null : TUMOR_DT_WEEKDAY_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_MONTH_NAME
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_MONTH_NAME() {
        return TUMOR_MONTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_MONTH_NAME
     *
     * @param TUMOR_MONTH_NAME the value for DVCBIO.TUMOR_V.TUMOR_MONTH_NAME
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_MONTH_NAME(String TUMOR_MONTH_NAME) {
        this.TUMOR_MONTH_NAME = TUMOR_MONTH_NAME == null ? null : TUMOR_MONTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_YEAR
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getTUMOR_YEAR() {
        return TUMOR_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_YEAR
     *
     * @param TUMOR_YEAR the value for DVCBIO.TUMOR_V.TUMOR_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_YEAR(Short TUMOR_YEAR) {
        this.TUMOR_YEAR = TUMOR_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_SEQ_NO
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_SEQ_NO
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getTUMOR_SEQ_NO() {
        return TUMOR_SEQ_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_SEQ_NO
     *
     * @param TUMOR_SEQ_NO the value for DVCBIO.TUMOR_V.TUMOR_SEQ_NO
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_SEQ_NO(Short TUMOR_SEQ_NO) {
        this.TUMOR_SEQ_NO = TUMOR_SEQ_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_MSK_CASE_STS
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_MSK_CASE_STS
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_MSK_CASE_STS() {
        return TUMOR_MSK_CASE_STS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_MSK_CASE_STS
     *
     * @param TUMOR_MSK_CASE_STS the value for DVCBIO.TUMOR_V.TUMOR_MSK_CASE_STS
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_MSK_CASE_STS(String TUMOR_MSK_CASE_STS) {
        this.TUMOR_MSK_CASE_STS = TUMOR_MSK_CASE_STS == null ? null : TUMOR_MSK_CASE_STS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_MSK_CLASS_OF_CASE
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_MSK_CLASS_OF_CASE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_MSK_CLASS_OF_CASE() {
        return TUMOR_MSK_CLASS_OF_CASE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_MSK_CLASS_OF_CASE
     *
     * @param TUMOR_MSK_CLASS_OF_CASE the value for DVCBIO.TUMOR_V.TUMOR_MSK_CLASS_OF_CASE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_MSK_CLASS_OF_CASE(String TUMOR_MSK_CLASS_OF_CASE) {
        this.TUMOR_MSK_CLASS_OF_CASE = TUMOR_MSK_CLASS_OF_CASE == null ? null : TUMOR_MSK_CLASS_OF_CASE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_CODE
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_HISTOLOGY_CODE() {
        return TUMOR_HISTOLOGY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_CODE
     *
     * @param TUMOR_HISTOLOGY_CODE the value for DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_HISTOLOGY_CODE(String TUMOR_HISTOLOGY_CODE) {
        this.TUMOR_HISTOLOGY_CODE = TUMOR_HISTOLOGY_CODE == null ? null : TUMOR_HISTOLOGY_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_DESC
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_HISTOLOGY_DESC() {
        return TUMOR_HISTOLOGY_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_DESC
     *
     * @param TUMOR_HISTOLOGY_DESC the value for DVCBIO.TUMOR_V.TUMOR_HISTOLOGY_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_HISTOLOGY_DESC(String TUMOR_HISTOLOGY_DESC) {
        this.TUMOR_HISTOLOGY_DESC = TUMOR_HISTOLOGY_DESC == null ? null : TUMOR_HISTOLOGY_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_SITE_CODE
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_SITE_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_SITE_CODE() {
        return TUMOR_SITE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_SITE_CODE
     *
     * @param TUMOR_SITE_CODE the value for DVCBIO.TUMOR_V.TUMOR_SITE_CODE
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_SITE_CODE(String TUMOR_SITE_CODE) {
        this.TUMOR_SITE_CODE = TUMOR_SITE_CODE == null ? null : TUMOR_SITE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_SITE_DESC
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_SITE_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_SITE_DESC() {
        return TUMOR_SITE_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_SITE_DESC
     *
     * @param TUMOR_SITE_DESC the value for DVCBIO.TUMOR_V.TUMOR_SITE_DESC
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_SITE_DESC(String TUMOR_SITE_DESC) {
        this.TUMOR_SITE_DESC = TUMOR_SITE_DESC == null ? null : TUMOR_SITE_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_DX_YEAR
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_DX_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getTUMOR_DX_YEAR() {
        return TUMOR_DX_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_DX_YEAR
     *
     * @param TUMOR_DX_YEAR the value for DVCBIO.TUMOR_V.TUMOR_DX_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_DX_YEAR(Short TUMOR_DX_YEAR) {
        this.TUMOR_DX_YEAR = TUMOR_DX_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_SURG_YEAR
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_SURG_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Short getTUMOR_SURG_YEAR() {
        return TUMOR_SURG_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_SURG_YEAR
     *
     * @param TUMOR_SURG_YEAR the value for DVCBIO.TUMOR_V.TUMOR_SURG_YEAR
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_SURG_YEAR(Short TUMOR_SURG_YEAR) {
        this.TUMOR_SURG_YEAR = TUMOR_SURG_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_LATERALITY
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_LATERALITY
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_LATERALITY() {
        return TUMOR_LATERALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_LATERALITY
     *
     * @param TUMOR_LATERALITY the value for DVCBIO.TUMOR_V.TUMOR_LATERALITY
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_LATERALITY(String TUMOR_LATERALITY) {
        this.TUMOR_LATERALITY = TUMOR_LATERALITY == null ? null : TUMOR_LATERALITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_DX
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_DX
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getTUMOR_PT_AGE_AT_DX() {
        return TUMOR_PT_AGE_AT_DX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_DX
     *
     * @param TUMOR_PT_AGE_AT_DX the value for DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_DX
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PT_AGE_AT_DX(Integer TUMOR_PT_AGE_AT_DX) {
        this.TUMOR_PT_AGE_AT_DX = TUMOR_PT_AGE_AT_DX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_SURG
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_SURG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public Integer getTUMOR_PT_AGE_AT_SURG() {
        return TUMOR_PT_AGE_AT_SURG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_SURG
     *
     * @param TUMOR_PT_AGE_AT_SURG the value for DVCBIO.TUMOR_V.TUMOR_PT_AGE_AT_SURG
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PT_AGE_AT_SURG(Integer TUMOR_PT_AGE_AT_SURG) {
        this.TUMOR_PT_AGE_AT_SURG = TUMOR_PT_AGE_AT_SURG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_M
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PATH_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_PATH_TNM_M() {
        return TUMOR_PATH_TNM_M;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_M
     *
     * @param TUMOR_PATH_TNM_M the value for DVCBIO.TUMOR_V.TUMOR_PATH_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PATH_TNM_M(String TUMOR_PATH_TNM_M) {
        this.TUMOR_PATH_TNM_M = TUMOR_PATH_TNM_M == null ? null : TUMOR_PATH_TNM_M.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_N
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PATH_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_PATH_TNM_N() {
        return TUMOR_PATH_TNM_N;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_N
     *
     * @param TUMOR_PATH_TNM_N the value for DVCBIO.TUMOR_V.TUMOR_PATH_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PATH_TNM_N(String TUMOR_PATH_TNM_N) {
        this.TUMOR_PATH_TNM_N = TUMOR_PATH_TNM_N == null ? null : TUMOR_PATH_TNM_N.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_T
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PATH_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_PATH_TNM_T() {
        return TUMOR_PATH_TNM_T;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_TNM_T
     *
     * @param TUMOR_PATH_TNM_T the value for DVCBIO.TUMOR_V.TUMOR_PATH_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PATH_TNM_T(String TUMOR_PATH_TNM_T) {
        this.TUMOR_PATH_TNM_T = TUMOR_PATH_TNM_T == null ? null : TUMOR_PATH_TNM_T.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_STG_GRP
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_PATH_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_PATH_STG_GRP() {
        return TUMOR_PATH_STG_GRP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_PATH_STG_GRP
     *
     * @param TUMOR_PATH_STG_GRP the value for DVCBIO.TUMOR_V.TUMOR_PATH_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_PATH_STG_GRP(String TUMOR_PATH_STG_GRP) {
        this.TUMOR_PATH_STG_GRP = TUMOR_PATH_STG_GRP == null ? null : TUMOR_PATH_STG_GRP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_M
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_CLIN_TNM_M() {
        return TUMOR_CLIN_TNM_M;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_M
     *
     * @param TUMOR_CLIN_TNM_M the value for DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_M
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_CLIN_TNM_M(String TUMOR_CLIN_TNM_M) {
        this.TUMOR_CLIN_TNM_M = TUMOR_CLIN_TNM_M == null ? null : TUMOR_CLIN_TNM_M.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_N
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_CLIN_TNM_N() {
        return TUMOR_CLIN_TNM_N;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_N
     *
     * @param TUMOR_CLIN_TNM_N the value for DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_N
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_CLIN_TNM_N(String TUMOR_CLIN_TNM_N) {
        this.TUMOR_CLIN_TNM_N = TUMOR_CLIN_TNM_N == null ? null : TUMOR_CLIN_TNM_N.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_T
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_CLIN_TNM_T() {
        return TUMOR_CLIN_TNM_T;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_T
     *
     * @param TUMOR_CLIN_TNM_T the value for DVCBIO.TUMOR_V.TUMOR_CLIN_TNM_T
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_CLIN_TNM_T(String TUMOR_CLIN_TNM_T) {
        this.TUMOR_CLIN_TNM_T = TUMOR_CLIN_TNM_T == null ? null : TUMOR_CLIN_TNM_T.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_STG_GRP
     *
     * @return the value of DVCBIO.TUMOR_V.TUMOR_CLIN_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public String getTUMOR_CLIN_STG_GRP() {
        return TUMOR_CLIN_STG_GRP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.TUMOR_V.TUMOR_CLIN_STG_GRP
     *
     * @param TUMOR_CLIN_STG_GRP the value for DVCBIO.TUMOR_V.TUMOR_CLIN_STG_GRP
     *
     * @mbggenerated Fri Nov 21 11:57:17 EST 2014
     */
    public void setTUMOR_CLIN_STG_GRP(String TUMOR_CLIN_STG_GRP) {
        this.TUMOR_CLIN_STG_GRP = TUMOR_CLIN_STG_GRP == null ? null : TUMOR_CLIN_STG_GRP.trim();
    }
}