package org.cbioportal.application.rest.response;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Map;

@Schema(name = "StructuralVariant", description = "Represents a structural variant")
public record StructuralVariantDTO(
    String uniqueSampleKey,
    String uniquePatientKey,
    String molecularProfileId,
    String sampleId,
    String patientId,
    String studyId,
    Integer site1EntrezGeneId,
    String site1HugoSymbol,
    String site1EnsemblTranscriptId,
    String site1Chromosome,
    Integer site1Position,
    String site1Contig,
    String site1Region,
    Integer site1RegionNumber,
    String site1Description,
    Integer site2EntrezGeneId,
    String site2HugoSymbol,
    String site2EnsemblTranscriptId,
    String site2Chromosome,
    Integer site2Position,
    String site2Contig,
    String site2Region,
    Integer site2RegionNumber,
    String site2Description,
    String site2EffectOnFrame,
    String ncbiBuild,
    String dnaSupport,
    String rnaSupport,
    Integer normalReadCount,
    Integer tumorReadCount,
    Integer normalVariantCount,
    Integer tumorVariantCount,
    Integer normalPairedEndReadCount,
    Integer tumorPairedEndReadCount,
    Integer normalSplitReadCount,
    Integer tumorSplitReadCount,
    String annotation,
    String breakpointType,
    String connectionType,
    String eventInfo,
    String variantClass,
    Integer length,
    String comments,
    String driverFilter,
    String driverFilterAnn,
    String driverTiersFilter,
    String driverTiersFilterAnn,
    String svStatus,
    Map<String, Map<String, Object>> namespaceColumns) {}
