<%--
  Created by IntelliJ IDEA.
  User: suny1
  Date: 6/15/15
  Time: 3:47 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page import="org.mskcc.cbio.portal.servlet.QueryBuilder" %>
<%@ page import="org.mskcc.cbio.portal.util.GlobalProperties" %>
<%
  String siteTitle = GlobalProperties.getTitle();
%>

<% request.setAttribute(QueryBuilder.HTML_TITLE, siteTitle+"::Portal Cancer Gene"); %>
<jsp:include page="WEB-INF/jsp/global/header.jsp" flush="true" />

<div class="cbioportal-cancer-gene-list">
    <h1>cBioPortal Cancer Gene List</h1>
    <span>A2ML1</span>
    <span>AADACL2</span>
    <span>AAMP</span>
    <span>AARS2</span>
    <span>ABCA9</span>
    <span>ABCB1</span>
    <span>ABCG4</span>
    <span>ABI1</span>
    <span>ABL1</span>
    <span>ABL2</span>
    <span>ACKR3</span>
    <span>ACSL3</span>
    <span>ACSL6</span>
    <span>ACTB</span>
    <span>ACVR1B</span>
    <span>ACVR2A</span>
    <span>AFF1</span>
    <span>AFF2</span>
    <span>AFF3</span>
    <span>AFF4</span>
    <span>AHNAK2</span>
    <span>AJUBA</span>
    <span>AK9</span>
    <span>AKAP9</span>
    <span>AKT1</span>
    <span>AKT2</span>
    <span>AKT3</span>
    <span>ALDH2</span>
    <span>ALK</span>
    <span>ALOX12B</span>
    <span>AMER1</span>
    <span>ANKRD12</span>
    <span>APC</span>
    <span>APCDD1</span>
    <span>APH1A</span>
    <span>AR</span>
    <span>ARAF</span>
    <span>ARFRP1</span>
    <span>ARHGAP26</span>
    <span>ARHGAP35</span>
    <span>ARHGEF12</span>
    <span>ARID1A</span>
    <span>ARID1B</span>
    <span>ARID2</span>
    <span>ARID5B</span>
    <span>ARNT</span>
    <span>ASCL4</span>
    <span>ASH2L</span>
    <span>ASMTL</span>
    <span>ASPSCR1</span>
    <span>ASXL1</span>
    <span>ASXL2</span>
    <span>ASXL3</span>
    <span>ATF1</span>
    <span>ATIC</span>
    <span>ATM</span>
    <span>ATN1</span>
    <span>ATP10A</span>
    <span>ATP1B4</span>
    <span>ATR</span>
    <span>ATRX</span>
    <span>AURKA</span>
    <span>AURKB</span>
    <span>AXIN1</span>
    <span>AXIN2</span>
    <span>AXL</span>
    <span>B2M</span>
    <span>B4GALT3</span>
    <span>BACH1</span>
    <span>BAP1</span>
    <span>BARD1</span>
    <span>BBC3</span>
    <span>BCL10</span>
    <span>BCL11A</span>
    <span>BCL11B</span>
    <span>BCL2</span>
    <span>BCL2L1</span>
    <span>BCL2L11</span>
    <span>BCL2L2</span>
    <span>BCL3</span>
    <span>BCL5</span>
    <span>BCL6</span>
    <span>BCL7A</span>
    <span>BCL9</span>
    <span>BCOR</span>
    <span>BCORL1</span>
    <span>BCR</span>
    <span>BIRC2</span>
    <span>BIRC3</span>
    <span>BLM</span>
    <span>BMPR1A</span>
    <span>BRAF</span>
    <span>BRCA1</span>
    <span>BRCA2</span>
    <span>BRD3</span>
    <span>BRD4</span>
    <span>BRIP1</span>
    <span>BRSK1</span>
    <span>BTG1</span>
    <span>BTG2</span>
    <span>BTK</span>
    <span>BTLA</span>
    <span>BUB1B</span>
    <span>C11ORF30</span>
    <span>C15ORF65</span>
    <span>C2ORF44</span>
    <span>CAD</span>
    <span>CALR</span>
    <span>CAMTA1</span>
    <span>CANT1</span>
    <span>CARD11</span>
    <span>CARS</span>
    <span>CASC5</span>
    <span>CASP8</span>
    <span>CBFA2T3</span>
    <span>CBFB</span>
    <span>CBL</span>
    <span>CBLB</span>
    <span>CBLC</span>
    <span>CCDC160</span>
    <span>CCDC6</span>
    <span>CCNB1IP1</span>
    <span>CCND1</span>
    <span>CCND2</span>
    <span>CCND3</span>
    <span>CCNE1</span>
    <span>CCNL1</span>
    <span>CCT6B</span>
    <span>CD22</span>
    <span>CD274</span>
    <span>CD276</span>
    <span>CD36</span>
    <span>CD58</span>
    <span>CD70</span>
    <span>CD74</span>
    <span>CD79A</span>
    <span>CD79B</span>
    <span>CDC42EP2</span>
    <span>CDC73</span>
    <span>CDH1</span>
    <span>CDH11</span>
    <span>CDK12</span>
    <span>CDK4</span>
    <span>CDK6</span>
    <span>CDK8</span>
    <span>CDKN1A</span>
    <span>CDKN1B</span>
    <span>CDKN2A</span>
    <span>CDKN2AP14ARF</span>
    <span>CDKN2AP16INK4A</span>
    <span>CDKN2B</span>
    <span>CDKN2C</span>
    <span>CDX2</span>
    <span>CEBPA</span>
    <span>CHCHD7</span>
    <span>CHD1</span>
    <span>CHD2</span>
    <span>CHD4</span>
    <span>CHEK1</span>
    <span>CHEK2</span>
    <span>CHIC2</span>
    <span>CHN1</span>
    <span>CHUK</span>
    <span>CIC</span>
    <span>CIITA</span>
    <span>CKS1B</span>
    <span>CLP1</span>
    <span>CLTC</span>
    <span>CLTCL1</span>
    <span>CNBP</span>
    <span>CNRIP1</span>
    <span>CNTRL</span>
    <span>COL11A1</span>
    <span>COL1A1</span>
    <span>COX6C</span>
    <span>CPS1</span>
    <span>CRBN</span>
    <span>CREB1</span>
    <span>CREB3L1</span>
    <span>CREB3L2</span>
    <span>CREBBP</span>
    <span>CRIPAK</span>
    <span>CRKL</span>
    <span>CRLF2</span>
    <span>CRTC1</span>
    <span>CRTC3</span>
    <span>CSF1R</span>
    <span>CSF3R</span>
    <span>CTCF</span>
    <span>CTLA4</span>
    <span>CTNNA1</span>
    <span>CTNNB1</span>
    <span>CUL3</span>
    <span>CUL4A</span>
    <span>CUL4B</span>
    <span>CUX1</span>
    <span>CXCR4</span>
    <span>CYLD</span>
    <span>CYP17A1</span>
    <span>D2HGDH</span>
    <span>DAXX</span>
    <span>DCHS1</span>
    <span>DCUN1D1</span>
    <span>DDB2</span>
    <span>DDIT3</span>
    <span>DDR2</span>
    <span>DDX10</span>
    <span>DDX3X</span>
    <span>DDX5</span>
    <span>DDX6</span>
    <span>DEK</span>
    <span>DICER1</span>
    <span>DIS3</span>
    <span>DKC1</span>
    <span>DKK1</span>
    <span>DKK2</span>
    <span>DKK3</span>
    <span>DKK4</span>
    <span>DMD</span>
    <span>DNAH12</span>
    <span>DNM2</span>
    <span>DNMT1</span>
    <span>DNMT3A</span>
    <span>DNMT3B</span>
    <span>DOCK2</span>
    <span>DOT1L</span>
    <span>DTX1</span>
    <span>DUSP2</span>
    <span>DUSP9</span>
    <span>DUX4L1</span>
    <span>E2F3</span>
    <span>EBF1</span>
    <span>ECT2L</span>
    <span>EED</span>
    <span>EGFL7</span>
    <span>EGFR</span>
    <span>EGFRVIII</span>
    <span>EGR3</span>
    <span>EIF1AX</span>
    <span>EIF2B1</span>
    <span>EIF4A2</span>
    <span>EIF4EBP1</span>
    <span>ELF3</span>
    <span>ELF4</span>
    <span>ELK4</span>
    <span>ELL</span>
    <span>ELN</span>
    <span>ELP2</span>
    <span>EML4</span>
    <span>EP300</span>
    <span>EPCAM</span>
    <span>EPHA10</span>
    <span>EPHA2</span>
    <span>EPHA3</span>
    <span>EPHA4</span>
    <span>EPHA5</span>
    <span>EPHA6</span>
    <span>EPHA7</span>
    <span>EPHA8</span>
    <span>EPHB1</span>
    <span>EPHB2</span>
    <span>EPHB3</span>
    <span>EPHB4</span>
    <span>EPHB6</span>
    <span>EPPK1</span>
    <span>EPS15</span>
    <span>ERBB2</span>
    <span>ERBB3</span>
    <span>ERBB4</span>
    <span>ERC1</span>
    <span>ERCC2</span>
    <span>ERCC3</span>
    <span>ERCC4</span>
    <span>ERCC5</span>
    <span>ERG</span>
    <span>ESCO1</span>
    <span>ESCO2</span>
    <span>ESR1</span>
    <span>ETS1</span>
    <span>ETV1</span>
    <span>ETV4</span>
    <span>ETV5</span>
    <span>ETV6</span>
    <span>EWSR1</span>
    <span>EXOSC6</span>
    <span>EXT1</span>
    <span>EXT2</span>
    <span>EZH2</span>
    <span>EZR</span>
    <span>FAF1</span>
    <span>FAM175A</span>
    <span>FAM46C</span>
    <span>FANCA</span>
    <span>FANCC</span>
    <span>FANCD2</span>
    <span>FANCE</span>
    <span>FANCF</span>
    <span>FANCG</span>
    <span>FANCI</span>
    <span>FANCL</span>
    <span>FANCM</span>
    <span>FAS</span>
    <span>FAT1</span>
    <span>FAT3</span>
    <span>FAT4</span>
    <span>FBXO11</span>
    <span>FBXO31</span>
    <span>FBXW7</span>
    <span>FCGR2B</span>
    <span>FCRL4</span>
    <span>FEV</span>
    <span>FGF10</span>
    <span>FGF12</span>
    <span>FGF14</span>
    <span>FGF19</span>
    <span>FGF23</span>
    <span>FGF3</span>
    <span>FGF4</span>
    <span>FGF6</span>
    <span>FGF7</span>
    <span>FGFR1</span>
    <span>FGFR1OP</span>
    <span>FGFR2</span>
    <span>FGFR3</span>
    <span>FGFR4</span>
    <span>FH</span>
    <span>FHIT</span>
    <span>FIP1L1</span>
    <span>FKBP1A</span>
    <span>FLCN</span>
    <span>FLI1</span>
    <span>FLT1</span>
    <span>FLT3</span>
    <span>FLT4</span>
    <span>FLYWCH1</span>
    <span>FNBP1</span>
    <span>FOXA1</span>
    <span>FOXA2</span>
    <span>FOXL2</span>
    <span>FOXO1</span>
    <span>FOXO3</span>
    <span>FOXO4</span>
    <span>FOXP1</span>
    <span>FRS2</span>
    <span>FSTL3</span>
    <span>FUBP1</span>
    <span>FUS</span>
    <span>FYN</span>
    <span>FZD10</span>
    <span>GADD45B</span>
    <span>GAS7</span>
    <span>GATA1</span>
    <span>GATA2</span>
    <span>GATA3</span>
    <span>GID4</span>
    <span>GLI1</span>
    <span>GLI3</span>
    <span>GMPS</span>
    <span>GNA11</span>
    <span>GNA12</span>
    <span>GNA13</span>
    <span>GNAQ</span>
    <span>GNAS</span>
    <span>GOLGA5</span>
    <span>GOLPH3</span>
    <span>GOPC</span>
    <span>GPC3</span>
    <span>GPHN</span>
    <span>GPR124</span>
    <span>GPS2</span>
    <span>GREM1</span>
    <span>GRIN2A</span>
    <span>GRM3</span>
    <span>GSK3B</span>
    <span>GTSE1</span>
    <span>H3F3A</span>
    <span>H3F3C</span>
    <span>HDAC1</span>
    <span>HDAC2</span>
    <span>HDAC4</span>
    <span>HDAC7</span>
    <span>HERPUD1</span>
    <span>HEY1</span>
    <span>HGF</span>
    <span>HIF1A</span>
    <span>HIP1</span>
    <span>HIST1H1C</span>
    <span>HIST1H1D</span>
    <span>HIST1H1E</span>
    <span>HIST1H2AC</span>
    <span>HIST1H2AG</span>
    <span>HIST1H2AL</span>
    <span>HIST1H2AM</span>
    <span>HIST1H2BC</span>
    <span>HIST1H2BD</span>
    <span>HIST1H2BJ</span>
    <span>HIST1H2BK</span>
    <span>HIST1H2BO</span>
    <span>HIST1H3A</span>
    <span>HIST1H3B</span>
    <span>HIST1H4I</span>
    <span>HLA-A</span>
    <span>HLA-B</span>
    <span>HLF</span>
    <span>HMGA1</span>
    <span>HMGA2</span>
    <span>HMGN2P46</span>
    <span>HNF1A</span>
    <span>HNRNPA2B1</span>
    <span>HOOK3</span>
    <span>HOXA11</span>
    <span>HOXA13</span>
    <span>HOXA9</span>
    <span>HOXC11</span>
    <span>HOXC13</span>
    <span>HOXD11</span>
    <span>HOXD13</span>
    <span>HRAS</span>
    <span>HSP90AA1</span>
    <span>HSP90AB1</span>
    <span>ICE1</span>
    <span>ICK</span>
    <span>ICOSLG</span>
    <span>ID3</span>
    <span>IDH1</span>
    <span>IDH2</span>
    <span>IFNGR1</span>
    <span>IGF1</span>
    <span>IGF1R</span>
    <span>IGF2</span>
    <span>IGFBP7</span>
    <span>IGH</span>
    <span>IGK</span>
    <span>IGL</span>
    <span>IKBKB</span>
    <span>IKBKE</span>
    <span>IKZF1</span>
    <span>IKZF2</span>
    <span>IKZF3</span>
    <span>IL10</span>
    <span>IL2</span>
    <span>IL21R</span>
    <span>IL6ST</span>
    <span>IL7R</span>
    <span>INHBA</span>
    <span>INPP4A</span>
    <span>INPP4B</span>
    <span>INPP5D</span>
    <span>INSR</span>
    <span>INSRR</span>
    <span>IRF1</span>
    <span>IRF4</span>
    <span>IRF8</span>
    <span>IRS1</span>
    <span>IRS2</span>
    <span>ITGAL</span>
    <span>ITK</span>
    <span>JAK1</span>
    <span>JAK2</span>
    <span>JAK3</span>
    <span>JARID2</span>
    <span>JAZF1</span>
    <span>JUN</span>
    <span>KAT6A</span>
    <span>KAT6B</span>
    <span>KCNJ5</span>
    <span>KDM2B</span>
    <span>KDM4C</span>
    <span>KDM5A</span>
    <span>KDM5C</span>
    <span>KDM6A</span>
    <span>KDR</span>
    <span>KDSR</span>
    <span>KEAP1</span>
    <span>KIAA1109</span>
    <span>KIAA1549</span>
    <span>KIF5B</span>
    <span>KIT</span>
    <span>KLF4</span>
    <span>KLF6</span>
    <span>KLHL6</span>
    <span>KLK2</span>
    <span>KMT2A</span>
    <span>KMT2B</span>
    <span>KMT2C</span>
    <span>KMT2D</span>
    <span>KRAS</span>
    <span>KTN1</span>
    <span>LASP1</span>
    <span>LATS1</span>
    <span>LATS2</span>
    <span>LCK</span>
    <span>LCP1</span>
    <span>LDHA</span>
    <span>LEF1</span>
    <span>LFNG</span>
    <span>LGR6</span>
    <span>LHFP</span>
    <span>LIFR</span>
    <span>LMO1</span>
    <span>LMO2</span>
    <span>LPP</span>
    <span>LRIG3</span>
    <span>LRP1B</span>
    <span>LRP5</span>
    <span>LRRK2</span>
    <span>LYL1</span>
    <span>MAF</span>
    <span>MAFB</span>
    <span>MAGED1</span>
    <span>MAGEE1</span>
    <span>MAGI2</span>
    <span>MALAT1</span>
    <span>MALT1</span>
    <span>MAML2</span>
    <span>MAP2K1</span>
    <span>MAP2K2</span>
    <span>MAP2K4</span>
    <span>MAP3K1</span>
    <span>MAP3K13</span>
    <span>MAP3K14</span>
    <span>MAP3K4</span>
    <span>MAP3K6</span>
    <span>MAP3K7</span>
    <span>MAP3K8</span>
    <span>MAP4K4</span>
    <span>MAPK1</span>
    <span>MAPK8IP1</span>
    <span>MAX</span>
    <span>MCL1</span>
    <span>MDC1</span>
    <span>MDM2</span>
    <span>MDM4</span>
    <span>MDS2</span>
    <span>MECOM</span>
    <span>MED12</span>
    <span>MEF2A</span>
    <span>MEF2B</span>
    <span>MEF2C</span>
    <span>MEN1</span>
    <span>MET</span>
    <span>MIB1</span>
    <span>MIR142</span>
    <span>MIR17HG</span>
    <span>MITF</span>
    <span>MKI67</span>
    <span>MKL1</span>
    <span>MLF1</span>
    <span>MLH1</span>
    <span>MLLT1</span>
    <span>MLLT10</span>
    <span>MLLT11</span>
    <span>MLLT3</span>
    <span>MLLT4</span>
    <span>MLLT6</span>
    <span>MLST8</span>
    <span>MN1</span>
    <span>MNX1</span>
    <span>MPL</span>
    <span>MRE11A</span>
    <span>MSH2</span>
    <span>MSH3</span>
    <span>MSH6</span>
    <span>MSI1</span>
    <span>MSI2</span>
    <span>MSN</span>
    <span>MTAP</span>
    <span>MTCP1</span>
    <span>MTOR</span>
    <span>MUC1</span>
    <span>MUTYH</span>
    <span>MYB</span>
    <span>MYC</span>
    <span>MYCL</span>
    <span>MYCN</span>
    <span>MYD88</span>
    <span>MYH11</span>
    <span>MYH9</span>
    <span>MYO18A</span>
    <span>MYOD1</span>
    <span>NACA</span>
    <span>NAV3</span>
    <span>NBN</span>
    <span>NCKIPSD</span>
    <span>NCOA1</span>
    <span>NCOA2</span>
    <span>NCOA3</span>
    <span>NCOA4</span>
    <span>NCOR1</span>
    <span>NCOR2</span>
    <span>NCSTN</span>
    <span>NDRG1</span>
    <span>NEFH</span>
    <span>NF1</span>
    <span>NF2</span>
    <span>NFE2L2</span>
    <span>NFE2L3</span>
    <span>NFIB</span>
    <span>NFKB1</span>
    <span>NFKB2</span>
    <span>NFKBIA</span>
    <span>NIN</span>
    <span>NKX2-1</span>
    <span>NKX3-1</span>
    <span>NLRP3</span>
    <span>NOD1</span>
    <span>NONO</span>
    <span>NOTCH1</span>
    <span>NOTCH2</span>
    <span>NOTCH3</span>
    <span>NOTCH4</span>
    <span>NPM1</span>
    <span>NR1H2</span>
    <span>NR3C1</span>
    <span>NR4A2</span>
    <span>NR4A3</span>
    <span>NRAS</span>
    <span>NSD1</span>
    <span>NT5C2</span>
    <span>NTRK1</span>
    <span>NTRK2</span>
    <span>NTRK3</span>
    <span>NUMA1</span>
    <span>NUP214</span>
    <span>NUP93</span>
    <span>NUP98</span>
    <span>NUTM1</span>
    <span>NUTM2A</span>
    <span>NUTM2B</span>
    <span>OBSCN</span>
    <span>OLIG2</span>
    <span>OMD</span>
    <span>OTX2</span>
    <span>P2RY8</span>
    <span>PAFAH1B2</span>
    <span>PAG1</span>
    <span>PAK1</span>
    <span>PAK3</span>
    <span>PAK7</span>
    <span>PALB2</span>
    <span>PARK2</span>
    <span>PARP1</span>
    <span>PARP2</span>
    <span>PARP3</span>
    <span>PARP4</span>
    <span>PASK</span>
    <span>PATZ1</span>
    <span>PAX3</span>
    <span>PAX5</span>
    <span>PAX7</span>
    <span>PAX8</span>
    <span>PBRM1</span>
    <span>PBX1</span>
    <span>PC</span>
    <span>PCBP1</span>
    <span>PCLO</span>
    <span>PCM1</span>
    <span>PCSK7</span>
    <span>PDCD1</span>
    <span>PDCD11</span>
    <span>PDCD1LG2</span>
    <span>PDE4DIP</span>
    <span>PDGFB</span>
    <span>PDGFRA</span>
    <span>PDGFRB</span>
    <span>PDK1</span>
    <span>PDPK1</span>
    <span>PDS5B</span>
    <span>PDYN</span>
    <span>PER1</span>
    <span>PHF6</span>
    <span>PHLDA1</span>
    <span>PHOX2B</span>
    <span>PICALM</span>
    <span>PIK3C2G</span>
    <span>PIK3C3</span>
    <span>PIK3CA</span>
    <span>PIK3CB</span>
    <span>PIK3CD</span>
    <span>PIK3CG</span>
    <span>PIK3R1</span>
    <span>PIK3R2</span>
    <span>PIK3R3</span>
    <span>PIM1</span>
    <span>PKM</span>
    <span>PLAG1</span>
    <span>PLCG2</span>
    <span>PLEC</span>
    <span>PLK2</span>
    <span>PMAIP1</span>
    <span>PMEL</span>
    <span>PML</span>
    <span>PMS1</span>
    <span>PMS2</span>
    <span>PNRC1</span>
    <span>POFUT1</span>
    <span>POGLUT1</span>
    <span>POLE</span>
    <span>POLQ</span>
    <span>POT1</span>
    <span>POU2AF1</span>
    <span>POU5F1</span>
    <span>PPARG</span>
    <span>PPP2R1A</span>
    <span>PPP6C</span>
    <span>PRCC</span>
    <span>PRDM1</span>
    <span>PRDM16</span>
    <span>PRDM2</span>
    <span>PREX2</span>
    <span>PRF1</span>
    <span>PRKAA2</span>
    <span>PRKAR1A</span>
    <span>PRKCI</span>
    <span>PRKDC</span>
    <span>PRRX1</span>
    <span>PRSS8</span>
    <span>PSIP1</span>
    <span>PTCH1</span>
    <span>PTEN</span>
    <span>PTK2</span>
    <span>PTPN11</span>
    <span>PTPN2</span>
    <span>PTPN22</span>
    <span>PTPN6</span>
    <span>PTPRD</span>
    <span>PTPRO</span>
    <span>PTPRS</span>
    <span>PTPRT</span>
    <span>RABEP1</span>
    <span>RAC1</span>
    <span>RAD21</span>
    <span>RAD50</span>
    <span>RAD51</span>
    <span>RAD51B</span>
    <span>RAD51C</span>
    <span>RAD51D</span>
    <span>RAD52</span>
    <span>RAD54L</span>
    <span>RAF1</span>
    <span>RALGDS</span>
    <span>RANBP17</span>
    <span>RAP1GDS1</span>
    <span>RARA</span>
    <span>RASA1</span>
    <span>RASGEF1A</span>
    <span>RB1</span>
    <span>RBM10</span>
    <span>RBM15</span>
    <span>RBMX</span>
    <span>RECQL4</span>
    <span>REL</span>
    <span>RELN</span>
    <span>RET</span>
    <span>RFWD2</span>
    <span>RHEB</span>
    <span>RHOA</span>
    <span>RHOH</span>
    <span>RICTOR</span>
    <span>RIT1</span>
    <span>RMI2</span>
    <span>RMRP</span>
    <span>RNF213</span>
    <span>RNF217-AS1</span>
    <span>RNF43</span>
    <span>ROR2</span>
    <span>ROS1</span>
    <span>RPA1</span>
    <span>RPGR</span>
    <span>RPL11</span>
    <span>RPL13</span>
    <span>RPL15</span>
    <span>RPL22</span>
    <span>RPL35A</span>
    <span>RPL5</span>
    <span>RPN1</span>
    <span>RPS14</span>
    <span>RPS19</span>
    <span>RPS26</span>
    <span>RPS6KA4</span>
    <span>RPS6KB1</span>
    <span>RPS6KB2</span>
    <span>RPTOR</span>
    <span>RSPO2</span>
    <span>RSPO3</span>
    <span>RUNX1</span>
    <span>RUNX1T1</span>
    <span>RYBP</span>
    <span>S1PR2</span>
    <span>SBDS</span>
    <span>SDC4</span>
    <span>SDHA</span>
    <span>SDHAF2</span>
    <span>SDHB</span>
    <span>SDHC</span>
    <span>SDHD</span>
    <span>SEMG1</span>
    <span>SEPT5</span>
    <span>SEPT6</span>
    <span>SEPT9</span>
    <span>SERP2</span>
    <span>SET</span>
    <span>SETBP1</span>
    <span>SETD2</span>
    <span>SF3B1</span>
    <span>SFPQ</span>
    <span>SGK1</span>
    <span>SH2B3</span>
    <span>SH2D1A</span>
    <span>SH3GL1</span>
    <span>SHQ1</span>
    <span>SIN3A</span>
    <span>SKP2</span>
    <span>SLC34A2</span>
    <span>SLC45A3</span>
    <span>SMAD2</span>
    <span>SMAD3</span>
    <span>SMAD4</span>
    <span>SMARCA1</span>
    <span>SMARCA4</span>
    <span>SMARCB1</span>
    <span>SMARCD1</span>
    <span>SMC1A</span>
    <span>SMC3</span>
    <span>SMO</span>
    <span>SNAP25</span>
    <span>SNED1</span>
    <span>SNX29</span>
    <span>SOCS1</span>
    <span>SOCS2</span>
    <span>SOCS3</span>
    <span>SOX10</span>
    <span>SOX17</span>
    <span>SOX2</span>
    <span>SOX4</span>
    <span>SOX9</span>
    <span>SPECC1</span>
    <span>SPEN</span>
    <span>SPOP</span>
    <span>SRC</span>
    <span>SRGAP3</span>
    <span>SRSF2</span>
    <span>SRSF3</span>
    <span>SS18</span>
    <span>SS18L1</span>
    <span>SSX1</span>
    <span>SSX2</span>
    <span>SSX4</span>
    <span>STAG1</span>
    <span>STAG2</span>
    <span>STAT3</span>
    <span>STAT4</span>
    <span>STAT5A</span>
    <span>STAT5B</span>
    <span>STAT6</span>
    <span>STK11</span>
    <span>STK40</span>
    <span>SUFU</span>
    <span>SUZ12</span>
    <span>SYK</span>
    <span>SYNE1</span>
    <span>TAF1</span>
    <span>TAF15</span>
    <span>TAF1L</span>
    <span>TAL1</span>
    <span>TAL2</span>
    <span>TBK1</span>
    <span>TBL1XR1</span>
    <span>TBX3</span>
    <span>TCEA1</span>
    <span>TCF12</span>
    <span>TCF3</span>
    <span>TCF7L2</span>
    <span>TCL1A</span>
    <span>TCL6</span>
    <span>TEK</span>
    <span>TERT</span>
    <span>TET1</span>
    <span>TET2</span>
    <span>TET3</span>
    <span>TFE3</span>
    <span>TFEB</span>
    <span>TFG</span>
    <span>TFPT</span>
    <span>TFRC</span>
    <span>TGFBR1</span>
    <span>TGFBR2</span>
    <span>THRAP3</span>
    <span>TICAM1</span>
    <span>TIPARP</span>
    <span>TLL2</span>
    <span>TLR4</span>
    <span>TLX1</span>
    <span>TLX3</span>
    <span>TMEM127</span>
    <span>TMEM30A</span>
    <span>TMPRSS2</span>
    <span>TMSB4XP8</span>
    <span>TNFAIP3</span>
    <span>TNFAIP6</span>
    <span>TNFRSF11A</span>
    <span>TNFRSF14</span>
    <span>TNFRSF17</span>
    <span>TNFSF9</span>
    <span>TNKS</span>
    <span>TOP1</span>
    <span>TOX</span>
    <span>TP53</span>
    <span>TP63</span>
    <span>TPM3</span>
    <span>TPM4</span>
    <span>TPR</span>
    <span>TPRX1</span>
    <span>TRA</span>
    <span>TRAF2</span>
    <span>TRAF3</span>
    <span>TRAF5</span>
    <span>TRAF7</span>
    <span>TRB</span>
    <span>TRD</span>
    <span>TRIM24</span>
    <span>TRIM27</span>
    <span>TRIM33</span>
    <span>TRIM7</span>
    <span>TRIOBP</span>
    <span>TRIP11</span>
    <span>TRRAP</span>
    <span>TSC1</span>
    <span>TSC2</span>
    <span>TSHR</span>
    <span>TSHZ2</span>
    <span>TSHZ3</span>
    <span>TTL</span>
    <span>TUSC3</span>
    <span>TYK2</span>
    <span>TYMS</span>
    <span>U2AF1</span>
    <span>U2AF2</span>
    <span>UHRF1BP1L</span>
    <span>USP6</span>
    <span>USP9X</span>
    <span>VHL</span>
    <span>VTCN1</span>
    <span>VTI1A</span>
    <span>WAS</span>
    <span>WDR90</span>
    <span>WHSC1</span>
    <span>WHSC1L1</span>
    <span>WIF1</span>
    <span>WISP3</span>
    <span>WNK1</span>
    <span>WRN</span>
    <span>WT1</span>
    <span>WWOX</span>
    <span>WWTR1</span>
    <span>XBP1</span>
    <span>XIAP</span>
    <span>XPA</span>
    <span>XPC</span>
    <span>XPO1</span>
    <span>XRCC3</span>
    <span>YAP1</span>
    <span>YES1</span>
    <span>YWHAE</span>
    <span>YY1AP1</span>
    <span>ZBTB16</span>
    <span>ZFHX3</span>
    <span>ZFP36L1</span>
    <span>ZMYM2</span>
    <span>ZMYM3</span>
    <span>ZNF132</span>
    <span>ZNF217</span>
    <span>ZNF24</span>
    <span>ZNF300</span>
    <span>ZNF331</span>
    <span>ZNF384</span>
    <span>ZNF521</span>
    <span>ZNF703</span>
    <span>ZNF750</span>
    <span>ZNF91</span>
    <span>ZRSR2</span>
</div>
</td>
<td width="172">
  <jsp:include page="WEB-INF/jsp/global/right_column.jsp" flush="true" />
</td>
</tr>
<tr>
  <td colspan="3">
    <jsp:include page="WEB-INF/jsp/global/footer.jsp" flush="true" />
  </td>
</tr>
</table>
</div>
</center>
</div>
</form>
<jsp:include page="WEB-INF/jsp/global/xdebug.jsp" flush="true" />
</body>
</html>
