name: Sanity checks
on: [push, pull_request]
jobs:
  build:
    name: Sanity Check
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout cbioportal repo'
        uses: actions/checkout@v2
        with:
          path: ./cbioportal
      - name: 'Run tests'
        working-directory: ./cbioportal
        run: |
          bash test/test_db_version.sh