name: Update POM for Snapshot Release

on:
  release:
    types:
      - published

jobs:
  update-pom:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup Git identity
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"

      - name: Download semver management tool
        run: |
          wget -q https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x semver

      - name: Update pom with snapshot release version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          SNAPSHOT_VERSION=$(./semver bump patch $VERSION)
          SNAPSHOT_TAG=v"$SNAPSHOT_VERSION"-SNAPSHOT
          sed -i "s|<version>\(.*\)-SNAPSHOT</version>|<version>$SNAPSHOT_TAG</version>|" pom.xml
          git add pom.xml
          git commit -m "Prepare for $SNAPSHOT_TAG"
          git push